#include <opal/video_packet.hpp>
#include <opal/video_reassembly.hpp>
#include <cassert>
#include <cstdint>
#include <vector>

static std::vector<opal::VideoPlainPacket> make_frame(std::uint64_t id,std::size_t bytes,std::uint16_t flags=0){std::vector<std::uint8_t> data(bytes);for(std::size_t i=0;i<data.size();++i)data[i]=static_cast<std::uint8_t>((i+id*13u)&0xffu);std::uint64_t sequence=id*1000;return opal::fragment_media_unit(opal::VideoMediaType::VideoH264,flags,5,77,id,id*16667,data,sequence,true);}
static bool feed_complete(opal::VideoReassembler&r,const std::vector<opal::VideoPlainPacket>&packets,opal::ReassembledFrame&complete){bool delivered=false;for(const auto&packet:packets)if(r.accept(packet,complete)==opal::ReassemblyStatus::Complete)delivered=true;return delivered;}

int main(){
    std::vector<std::uint8_t> expected(100*1024);for(std::size_t i=0;i<expected.size();++i)expected[i]=static_cast<std::uint8_t>((i+13u)&0xffu);std::uint64_t sequence=1000;auto packets=opal::fragment_media_unit(opal::VideoMediaType::VideoH264,opal::FrameKeyframe,5,77,1,16667,expected,sequence,true);opal::VideoReassembler reassembler;reassembler.reset(5,77);opal::ReassembledFrame complete;bool completed=false;for(const auto &packet:packets){if(packet.header.media_type!=opal::VideoMediaType::Fec&&packet.header.fragment_index==3)continue;auto status=reassembler.accept(packet,complete);if(status==opal::ReassemblyStatus::Complete){completed=true;break;}}assert(completed&&complete.data==expected&&complete.frame_id==1&&complete.keyframe);

    reassembler.reset(5,77);completed=false;for(const auto &packet:packets){if(packet.header.media_type!=opal::VideoMediaType::Fec&&(packet.header.fragment_index==2||packet.header.fragment_index==3))continue;if(reassembler.accept(packet,complete)==opal::ReassemblyStatus::Complete)completed=true;}assert(!completed);

    std::vector<std::uint8_t> tiny_expected(500);for(std::size_t i=0;i<tiny_expected.size();++i)tiny_expected[i]=static_cast<std::uint8_t>((i+91u)&0xffu);sequence=60000;auto tiny_packets=opal::fragment_media_unit(opal::VideoMediaType::VideoH264,opal::FrameKeyframe,5,77,60,1000020,tiny_expected,sequence,true);assert(tiny_packets.size()==2);reassembler.reset(5,77);completed=false;for(const auto &packet:tiny_packets){if(packet.header.media_type!=opal::VideoMediaType::Fec)continue;if(reassembler.accept(packet,complete)==opal::ReassemblyStatus::Complete){completed=true;break;}}assert(completed&&complete.data==tiny_expected&&complete.frame_id==60&&complete.keyframe);

    reassembler.reset(5,77);auto startup_p=make_frame(40,500);bool startup_complete=false,startup_need_idr=false;for(const auto&packet:startup_p){auto status=reassembler.accept(packet,complete);if(status==opal::ReassemblyStatus::Complete)startup_complete=true;if(status==opal::ReassemblyStatus::NeedIdr)startup_need_idr=true;}assert(!startup_complete&&startup_need_idr);

    reassembler.reset(5,77);auto initial=make_frame(49,500,opal::FrameKeyframe);assert(feed_complete(reassembler,initial,complete));auto lost_reference=make_frame(50,opal::kVideoDataFragmentBytes+100);assert(reassembler.accept(lost_reference.front(),complete)==opal::ReassemblyStatus::Incomplete);auto next_reference=make_frame(51,500);bool next_complete=false,need_idr=false;for(const auto &packet:next_reference){auto status=reassembler.accept(packet,complete);if(status==opal::ReassemblyStatus::Complete)next_complete=true;if(status==opal::ReassemblyStatus::NeedIdr)need_idr=true;}assert(!next_complete&&need_idr);auto dependent=make_frame(53,500);bool dependent_complete=false;for(const auto &packet:dependent)if(reassembler.accept(packet,complete)==opal::ReassemblyStatus::Complete)dependent_complete=true;assert(!dependent_complete);auto recovery=make_frame(54,500,opal::FrameKeyframe);bool recovery_complete=false;for(const auto &packet:recovery){if(reassembler.accept(packet,complete)==opal::ReassemblyStatus::Complete){recovery_complete=true;assert(complete.keyframe);}}assert(recovery_complete);bool late_old_complete=false;for(const auto&packet:lost_reference)if(reassembler.accept(packet,complete)==opal::ReassemblyStatus::Complete)late_old_complete=true;assert(!late_old_complete);

    reassembler.reset(5,77);auto gap_base=make_frame(100,500,opal::FrameKeyframe);assert(feed_complete(reassembler,gap_base,complete));auto after_whole_loss=make_frame(102,500);bool gap_need_idr=false,gap_complete=false;for(const auto&packet:after_whole_loss){auto status=reassembler.accept(packet,complete);if(status==opal::ReassemblyStatus::NeedIdr)gap_need_idr=true;if(status==opal::ReassemblyStatus::Complete)gap_complete=true;}assert(gap_need_idr&&!gap_complete);auto gap_key=make_frame(103,500,opal::FrameKeyframe);assert(feed_complete(reassembler,gap_key,complete));

    reassembler.reset(5,77);auto bound_key=make_frame(9,500,opal::FrameKeyframe);assert(feed_complete(reassembler,bound_key,complete));opal::ReassemblyStatus fourth=opal::ReassemblyStatus::Incomplete;for(std::uint64_t id=10;id<14;++id){auto frame=make_frame(id,opal::kVideoDataFragmentBytes+100);for(const auto &packet:frame){if(packet.header.media_type!=opal::VideoMediaType::Fec&&packet.header.fragment_index==0){fourth=reassembler.accept(packet,complete);break;}}}assert(reassembler.frames_in_flight()<=3);assert(reassembler.bytes_in_flight()<=16u*1024u*1024u);assert(fourth==opal::ReassemblyStatus::NeedIdr);

    reassembler.reset(5,77);opal::VideoPlainPacket oversized;oversized.header.generation=5;oversized.header.session_id=77;oversized.header.frame_id=20;oversized.header.fragment_count=1;oversized.header.payload_length=static_cast<std::uint16_t>(opal::kVideoPlaintextBytes);oversized.payload.resize(opal::kVideoPlaintextBytes+1);assert(reassembler.accept(oversized,complete)==opal::ReassemblyStatus::Ignored);assert(reassembler.bytes_in_flight()==0);

    reassembler.reset(5,77);auto reset_key=make_frame(29,500,opal::FrameKeyframe);assert(feed_complete(reassembler,reset_key,complete));auto old=make_frame(30,opal::kVideoDataFragmentBytes+10);for(const auto &packet:old){if(packet.header.media_type!=opal::VideoMediaType::Fec){reassembler.accept(packet,complete);break;}}assert(reassembler.frames_in_flight()==1);reassembler.reset(6,88);assert(reassembler.frames_in_flight()==0&&reassembler.bytes_in_flight()==0);assert(reassembler.accept(old.front(),complete)==opal::ReassemblyStatus::Ignored);

    reassembler.reset(5,77);for(std::uint64_t cycle=1;cycle<=128;++cycle){auto frame=make_frame(1000+cycle,700,opal::FrameKeyframe);assert(feed_complete(reassembler,frame,complete));assert(reassembler.frames_in_flight()==0);assert(reassembler.bytes_in_flight()==0);}return 0;
}
