#include <opal/tailnet.hpp>
#include <cassert>
#include <fstream>
#include <iterator>
#include <string>

static std::string read_all(const char*path){std::ifstream in(path);assert(in.good());return std::string(std::istreambuf_iterator<char>(in),std::istreambuf_iterator<char>());}
int main(){
    assert(opal::is_tailnet_ipv4("100.64.0.1"));assert(opal::is_tailnet_ipv4("100.127.255.254"));assert(!opal::is_tailnet_ipv4("100.63.255.255"));assert(!opal::is_tailnet_ipv4("100.128.0.1"));assert(!opal::is_tailnet_ipv4("192.168.178.107"));assert(!opal::is_tailnet_ipv4("not-an-ip"));
    const auto peers=opal::parse_tailnet_status_ipv4s("100.70.1.2 desktop user@ linux active; direct 1.2.3.4:41641\n100.90.4.5 laptop user@ linux idle; tx 1 rx 2\nfd7a:115c::1 phone user@ iOS -\n100.70.1.2 desktop user@ linux active\n");assert(peers.size()==2&&peers[0]=="100.70.1.2"&&peers[1]=="100.90.4.5");
    static_assert(opal::kTailnetDiscoveryTimeoutMs>=3000);
    static_assert(opal::kTailnetPeerHandshakeTimeoutMs>=5000);
    const auto header=read_all("include/opal/session.hpp");const auto session=read_all("src/session.cpp");const auto host=read_all("src/host.cpp");const auto client=read_all("src/client.cpp");const auto system=read_all("src/system.cpp");const auto setup=read_all("src/setup.cpp");
    assert(header.find("rendezvous_id")!=std::string::npos);assert(header.find("expected_host_public_key")!=std::string::npos);assert(header.find("tailnet_address")!=std::string::npos);assert(header.find("remote_tailnet_address")!=std::string::npos);assert(header.find("control_token")==std::string::npos);assert(header.find("tunneled")==std::string::npos);
    assert(session.find("BootstrapPath { Unset")!=std::string::npos);assert(session.find("BootstrapPath::None")==std::string::npos);assert(session.find("discover_local_host")!=std::string::npos);assert(session.find("local_discovery_enabled")!=std::string::npos);assert(session.find("tailnet_peer_ipv4s")!=std::string::npos);assert(session.find("discovery=tailnet candidates=")!=std::string::npos);assert(session.find("discovery=tailnet")!=std::string::npos);assert(session.find("local_tailnet_ipv4")!=std::string::npos);assert(session.find("tailnet-direct")!=std::string::npos);assert(session.find("kTailnetDiscoveryTimeoutMs")!=std::string::npos);assert(session.find("kTailnetPeerHandshakeTimeoutMs")!=std::string::npos);assert(session.find("RendezvousClient")!=std::string::npos);assert(session.find("host not found on LAN")!=std::string::npos);assert(session.find("PeerSession")!=std::string::npos);assert(session.find("start_native")!=std::string::npos);assert(session.find("generation")!=std::string::npos);assert(session.find("TunnelAccessHandle")==std::string::npos);assert(session.find("connect_tls")==std::string::npos);assert(session.find("tunnel_access")==std::string::npos);assert(session.find("zrok")==std::string::npos);
    const auto connect_begin=session.find("bool connect_generation");const auto healthy_begin=session.find("bool current_healthy",connect_begin);assert(connect_begin!=std::string::npos&&healthy_begin!=std::string::npos&&healthy_begin>connect_begin);const auto connect_source=session.substr(connect_begin,healthy_begin-connect_begin);assert(connect_source.find("pairing_password_provider()")==std::string::npos);const auto lan_pos=connect_source.find("discover_local_host(options.rendezvous_id,options.client_public_key,local");const auto peer_scan_pos=connect_source.find("tailnet_peer_ipv4s()");const auto rendezvous_pos=connect_source.find("RendezvousClient rendezvous");assert(lan_pos!=std::string::npos&&peer_scan_pos!=std::string::npos&&rendezvous_pos!=std::string::npos&&lan_pos<peer_scan_pos&&peer_scan_pos<rendezvous_pos);
    const auto start_begin=session.find("bool start(){");const auto stop_begin=session.find("void stop(){",start_begin);assert(start_begin!=std::string::npos&&stop_begin!=std::string::npos&&stop_begin>start_begin);const auto start_source=session.substr(start_begin,stop_begin-start_begin);const auto provider_call=start_source.find("pairing_password_provider()");const auto connect_call=start_source.find("connect_generation(1,true)");assert(provider_call!=std::string::npos&&connect_call!=std::string::npos&&provider_call<connect_call);
    assert(host.find("local_discovery_loop")!=std::string::npos);assert(host.find("local_tailnet_ipv4")!=std::string::npos);assert(host.find("HOST_META ")!=std::string::npos);assert(host.find("register_host")!=std::string::npos);assert(host.find("wait_offer")!=std::string::npos);assert(host.find("PeerSession")!=std::string::npos);assert(host.find("start_native")!=std::string::npos);assert(host.find("tunnel_host")==std::string::npos);assert(host.find("server_tls_context")==std::string::npos);assert(host.find("listen_tcp")==std::string::npos);assert(host.find("zrok")==std::string::npos);
    assert(client.find("parse_connection_code")!=std::string::npos);assert(client.find("host_public_key")!=std::string::npos);assert(client.find("tailnet_address")!=std::string::npos);assert(client.find("remote_tailnet_address")!=std::string::npos);assert(client.find("tunnel_connection_code")==std::string::npos);assert(client.find("zrok:")==std::string::npos);
    assert(system.find("curl -fsSL https://tailscale.com/install.sh | sh")!=std::string::npos);assert(system.find("sudo tailscale up")!=std::string::npos);assert(system.find("tailscale ip -4")!=std::string::npos);assert(setup.find("prepare_tailnet()")!=std::string::npos);assert(setup.find("ensure_tailnet()")!=std::string::npos);
    return 0;
}
