#include <opal/client.hpp>
#include <opal/config.hpp>
#include <opal/crypto.hpp>
#include <opal/input.hpp>
#include <opal/rendezvous_protocol.hpp>
#include <opal/session.hpp>
#include <X11/Xlib.h>
#include <X11/keysym.h>
#include <X11/extensions/XInput2.h>
#include <linux/input-event-codes.h>
#include <chrono>
#include <iostream>
#include <thread>

namespace opal {
namespace {

void sync_generation(SessionSupervisor&session,HeldInputState&held,unsigned long&generation){auto current=session.control_generation();if(current==generation)return;held.release_commands();generation=current;}
bool setup_xinput2(Display*d,Window root,int&opcode){int event=0,error=0;if(!XQueryExtension(d,"XInputExtension",&opcode,&event,&error))return false;int major=2,minor=0;if(XIQueryVersion(d,&major,&minor)!=Success||major<2)return false;unsigned char mask[XIMaskLen(XI_LASTEVENT)]{};XISetMask(mask,XI_RawKeyPress);XISetMask(mask,XI_RawKeyRelease);XISetMask(mask,XI_RawButtonPress);XISetMask(mask,XI_RawButtonRelease);XIEventMask selection{XIAllMasterDevices,static_cast<int>(sizeof(mask)),mask};if(XISelectEvents(d,root,&selection,1)!=Success)return false;XFlush(d);return true;}
std::string pointer_command_for(SessionSupervisor&session,int x,int y,int width,int height){return video_pointer_command(x,y,width,height,session.remote_width(),session.remote_height());}
bool send_pointer_position(Display*d,Window root,int width,int height,SessionSupervisor&session){Window returned_root=None,child=None;int root_x=0,root_y=0,win_x=0,win_y=0;unsigned int mask=0;if(!XQueryPointer(d,root,&returned_root,&child,&root_x,&root_y,&win_x,&win_y,&mask))return true;auto command=pointer_command_for(session,root_x,root_y,width,height);return command.empty()||session.send_input(command);}
bool send_pointer_position(int x,int y,int width,int height,SessionSupervisor&session){auto command=pointer_command_for(session,x,y,width,height);return command.empty()||session.send_input(command);}
bool send_key_event(SessionSupervisor&session,HeldInputState&held,unsigned long&generation,unsigned int keycode,bool down,bool&run,bool&release_capture){sync_generation(session,held,generation);int code=linux_keycode_from_x11(keycode);if(code<=0)return true;if(down){const auto chord=client_control_chord(held,code);if(chord==ClientControlChord::Quit){run=false;return true;}if(chord==ClientControlChord::ReleaseCapture){release_capture=true;return true;}}if(down)held.press_key(code);else held.release_key(code);return session.send_input("KEY "+std::to_string(code)+" "+(down?"1":"0"));}
void release_held(SessionSupervisor&session,HeldInputState&held,unsigned long&generation){sync_generation(session,held,generation);for(const auto&command:held.release_commands())session.send_input(command);}
int grab_input(Display*d,Window root,long pointer_mask){int keyboard_grab=XGrabKeyboard(d,root,True,GrabModeAsync,GrabModeAsync,CurrentTime);(void)XGrabPointer(d,root,True,static_cast<unsigned int>(pointer_mask),GrabModeAsync,GrabModeAsync,None,None,CurrentTime);XFlush(d);return keyboard_grab;}
void ungrab_input(Display*d){XUngrabKeyboard(d,CurrentTime);XUngrabPointer(d,CurrentTime);XFlush(d);}
bool wait_for_reacquire_click(Display*d,Window root,SessionSupervisor&session,long pointer_mask,int&keyboard_grab){bool armed=false;while(session.running()){const Window video=static_cast<Window>(session.presentation_window());if(video!=None){XWindowAttributes wa{};Window returned_root=None,child=None;int root_x=0,root_y=0,win_x=0,win_y=0;unsigned int mask=0;if(XGetWindowAttributes(d,video,&wa)&&XQueryPointer(d,video,&returned_root,&child,&root_x,&root_y,&win_x,&win_y,&mask)){const bool inside=win_x>=0&&win_y>=0&&win_x<wa.width&&win_y<wa.height;const bool button_down=(mask&(Button1Mask|Button2Mask|Button3Mask))!=0;if(!armed&&inside&&button_down)armed=true;else if(armed&&!button_down){XSync(d,True);keyboard_grab=grab_input(d,root,pointer_mask);return true;}}}std::this_thread::sleep_for(std::chrono::milliseconds(5));}return false;}

void run_xinput2_control(Display*d,Window root,int opcode,SessionSupervisor&session){XWindowAttributes wa{};if(!XGetWindowAttributes(d,root,&wa)||wa.width<=0||wa.height<=0)return;HeldInputState held;unsigned long generation=session.control_generation();int keyboard_grab=grab_input(d,root,PointerMotionMask);send_pointer_position(d,root,wa.width,wa.height,session);bool run=true;while(run&&session.running()){XEvent event;XNextEvent(d,&event);sync_generation(session,held,generation);bool release_capture=false;if(event.type==KeyPress||event.type==KeyRelease){bool down=event.type==KeyPress;if(!send_key_event(session,held,generation,event.xkey.keycode,down,run,release_capture)&&!session.running())run=false;if(release_capture){release_held(session,held,generation);ungrab_input(d);if(!wait_for_reacquire_click(d,root,session,PointerMotionMask,keyboard_grab))run=false;else send_pointer_position(d,root,wa.width,wa.height,session);}continue;}if(event.type==MotionNotify){if(!send_pointer_position(event.xmotion.x_root,event.xmotion.y_root,wa.width,wa.height,session)&&!session.running())run=false;continue;}if(event.xcookie.type!=GenericEvent||event.xcookie.extension!=opcode)continue;if(!XGetEventData(d,&event.xcookie))continue;auto*raw=static_cast<XIRawEvent*>(event.xcookie.data);bool send_ok=true;switch(event.xcookie.evtype){case XI_RawKeyPress:case XI_RawKeyRelease:if(keyboard_grab!=GrabSuccess)send_ok=send_key_event(session,held,generation,static_cast<unsigned int>(raw->detail),event.xcookie.evtype==XI_RawKeyPress,run,release_capture);break;case XI_RawButtonPress:case XI_RawButtonRelease:{send_ok=send_pointer_position(d,root,wa.width,wa.height,session);int button=raw->detail;bool down=event.xcookie.evtype==XI_RawButtonPress;if(send_ok&&(button==4||button==5)&&down)send_ok=session.send_input("WHEEL "+std::to_string(button==4?1:-1));else if(send_ok&&button>=1&&button<=3){if(down)held.press_button(button);else held.release_button(button);send_ok=session.send_input("BUTTON "+std::to_string(button)+" "+(down?"1":"0"));}break;}default:break;}XFreeEventData(d,&event.xcookie);if(release_capture){release_held(session,held,generation);ungrab_input(d);if(!wait_for_reacquire_click(d,root,session,PointerMotionMask,keyboard_grab))run=false;else send_pointer_position(d,root,wa.width,wa.height,session);}if(!send_ok&&!session.running())run=false;}release_held(session,held,generation);ungrab_input(d);}

void run_x11_fallback_control(Display*d,Window root,SessionSupervisor&session){XWindowAttributes wa{};if(!XGetWindowAttributes(d,root,&wa)||wa.width<=0||wa.height<=0)return;HeldInputState held;unsigned long generation=session.control_generation();int keyboard_grab=grab_input(d,root,PointerMotionMask|ButtonPressMask|ButtonReleaseMask);send_pointer_position(d,root,wa.width,wa.height,session);bool run=true;while(run&&session.running()){XEvent e;XNextEvent(d,&e);sync_generation(session,held,generation);bool release_capture=false;if(e.type==KeyPress||e.type==KeyRelease){bool down=e.type==KeyPress;if(!send_key_event(session,held,generation,e.xkey.keycode,down,run,release_capture)&&!session.running()){run=false;break;}if(release_capture){release_held(session,held,generation);ungrab_input(d);if(!wait_for_reacquire_click(d,root,session,PointerMotionMask|ButtonPressMask|ButtonReleaseMask,keyboard_grab)){run=false;break;}send_pointer_position(d,root,wa.width,wa.height,session);}}else if(e.type==MotionNotify){if(!send_pointer_position(e.xmotion.x_root,e.xmotion.y_root,wa.width,wa.height,session)&&!session.running()){run=false;break;}}else if(e.type==ButtonPress||e.type==ButtonRelease){int b=e.xbutton.button;bool down=e.type==ButtonPress;bool ok=send_pointer_position(e.xbutton.x_root,e.xbutton.y_root,wa.width,wa.height,session);if(ok&&(b==4||b==5)&&down)ok=session.send_input("WHEEL "+std::to_string(b==4?1:-1));else if(ok&&b<=3){if(down)held.press_button(b);else held.release_button(b);ok=session.send_input("BUTTON "+std::to_string(b)+" "+(down?"1":"0"));}if(!ok&&!session.running()){run=false;break;}}}release_held(session,held,generation);ungrab_input(d);(void)keyboard_grab;}

int error_code_for(const std::string&message){if(message.find("identity")!=std::string::npos)return 3;if(message.find("authentication")!=std::string::npos||message.find("pairing")!=std::string::npos)return 4;if(message.find("rendezvous")!=std::string::npos||message.find("offline")!=std::string::npos)return 2;return 1;}
bool saved_legacy(const Ini&hosts,const std::string&name){return hosts.get(name,"rendezvous_id").empty()&&!hosts.get(name,"address").empty();}
}

int hosts_add(const std::string&name,const std::string&address,const std::string&mac){auto p=Paths::load();ensure_layout(p);std::string id;if(!parse_connection_code(address,id)){std::cerr<<"host must be an OPAL connection code (opal:XXXX-XXXX-XXXX)\n";return 1;}Ini h;h.load(p.hosts);h.set(name,"rendezvous_id",id);h.set(name,"connection_code",format_connection_code(id));h.set(name,"paired","false");if(!mac.empty())h.set(name,"mac",mac);if(!h.save(p.hosts))return 1;std::cout<<"saved host "<<name<<" -> "<<format_connection_code(id)<<"\n";return 0;}
int hosts_list(){auto p=Paths::load();Ini h;if(!h.load(p.hosts)){std::cout<<"No saved hosts.\n";return 0;}for(auto&[s,v]:h.sections())if(!s.empty()){auto id=h.get(s,"rendezvous_id");std::cout<<s<<(id.empty()?"  legacy (re-pair required)":"  "+format_connection_code(id))<<"\n";}return 0;}

int client_connect(const std::string&target_in,const std::string&password_arg,const StreamOptions&stream){
    auto p=Paths::load();ensure_layout(p);if(!ensure_identity(p.identity_key,p.identity_pub)){std::cerr<<"client identity generation failed\n";return 1;}Ini hosts;hosts.load(p.hosts);const bool saved=hosts.sections().count(target_in)>0;std::string rendezvous_id,expected_host_key,tailnet_address;
    if(saved){if(saved_legacy(hosts,target_in)){std::cerr<<"saved host uses an obsolete OPAL host format; remove it and pair again with its current OPAL connection code\n";return 2;}rendezvous_id=hosts.get(target_in,"rendezvous_id");expected_host_key=hosts.get(target_in,"host_public_key");tailnet_address=hosts.get(target_in,"tailnet_address");}else if(!parse_connection_code(target_in,rendezvous_id)){std::cerr<<"invalid OPAL connection code; expected opal:XXXX-XXXX-XXXX\n";return 2;}
    if(rendezvous_id.empty()){std::cerr<<"saved OPAL host has no rendezvous identity\n";return 2;}
    SessionOptions options;options.rendezvous_id=rendezvous_id;options.expected_host_public_key=expected_host_key;options.tailnet_address=tailnet_address;options.client_public_key=public_key_hex(p.identity_pub);options.client_private_key_path=p.identity_key.string();options.paired=saved&&hosts.get(target_in,"paired")=="true"&&!expected_host_key.empty();options.pairing_password=password_arg;options.label=saved?target_in:"client";options.stream=stream;
    if(!options.paired&&options.pairing_password.empty())options.pairing_password_provider=[](){std::string password;std::cout<<"Pairing password: "<<std::flush;std::cin>>password;return password;};
    SessionSupervisor session(std::move(options));if(!session.start()){auto message=session.last_error();if(message.empty())message="cannot connect to OPAL host";std::cerr<<message<<"\n";return error_code_for(message);}

    const std::string section=saved?target_in:format_connection_code(rendezvous_id);hosts.set(section,"rendezvous_id",rendezvous_id);hosts.set(section,"connection_code",format_connection_code(rendezvous_id));hosts.set(section,"host_public_key",session.host_public_key());hosts.set(section,"paired",session.paired()?"true":"false");auto learned_mac=session.remote_mac();if(!learned_mac.empty())hosts.set(section,"mac",learned_mac);auto learned_tailnet=session.remote_tailnet_address();if(!learned_tailnet.empty())hosts.set(section,"tailnet_address",learned_tailnet);if(hosts.get(section,"mouse_sensitivity").empty())hosts.set(section,"mouse_sensitivity","1.0");hosts.save(p.hosts);

    for(int i=0;i<100&&!session.media_started()&&session.running();++i){
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
    if(!session.media_started()){auto message=session.last_error();std::cerr<<(message.empty()?"direct video did not start":message)<<"\n";session.stop();return 1;}
    learned_tailnet=session.remote_tailnet_address();if(!learned_tailnet.empty()){hosts.set(section,"tailnet_address",learned_tailnet);hosts.save(p.hosts);}
    std::cout<<"Connected. Ctrl+Alt+Shift+W releases input; click the OPAL screen to capture again. Ctrl+Alt+Shift+Q quits.\n";if(const char*d=std::getenv("OPAL_DEBUG");d&&*d&&std::string(d)!="0")std::cerr<<"OPAL connection path="<<session.path_name()<<"\n";
    Display*d=XOpenDisplay(nullptr);if(!d){std::cerr<<"DISPLAY unavailable; direct video cannot accept local input\n";while(session.running())std::this_thread::sleep_for(std::chrono::milliseconds(500));session.stop();return 0;}Window root=DefaultRootWindow(d);int xi_opcode=0;if(setup_xinput2(d,root,xi_opcode))run_xinput2_control(d,root,xi_opcode,session);else run_x11_fallback_control(d,root,session);XCloseDisplay(d);session.stop();return 0;
}
int client_connect(const std::string&target_in,const std::string&password_arg){return client_connect(target_in,password_arg,{});}
}
