#include <opal/peer_session.hpp>
#include <opal/crypto.hpp>
#include <opal/reliable_control.hpp>
#include <opal/session_packet.hpp>
#include <opal/video_crypto.hpp>

#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <cstdlib>
#include <cstring>
#include <mutex>
#include <sstream>
#include <thread>
#include <utility>
#include <vector>

namespace opal { namespace {
using Clock=std::chrono::steady_clock;

std::uint64_t monotonic_ms(){return static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::milliseconds>(Clock::now().time_since_epoch()).count());}
int remaining_ms(Clock::time_point deadline){const auto now=Clock::now();if(now>=deadline)return 0;return std::max(1,static_cast<int>(std::chrono::duration_cast<std::chrono::milliseconds>(deadline-now).count()));}
std::uint32_t read_magic(std::span<const std::uint8_t>b){if(b.size()<4)return 0;return(static_cast<std::uint32_t>(b[0])<<24)|(static_cast<std::uint32_t>(b[1])<<16)|(static_cast<std::uint32_t>(b[2])<<8)|b[3];}
std::uint64_t numeric_session_id(const std::string&hex_id){const auto bytes=unhex(hex_id);if(bytes.size()!=16)return 0;std::uint64_t value=0;for(int i=0;i<8;++i)value=(value<<8)|bytes[static_cast<std::size_t>(i)];return value?value:1;}
std::vector<std::string> fields(std::string_view text){std::istringstream in{std::string(text)};std::vector<std::string>out;std::string v;while(in>>v)out.push_back(std::move(v));return out;}
VideoKeys video_keys(const PeerChannelKeys&keys){VideoKeys result;result.send_key=keys.send_key;result.recv_key=keys.recv_key;result.send_nonce_base=keys.send_nonce_base;result.recv_nonce_base=keys.recv_nonce_base;return result;}
bool same_source(const sockaddr_storage&a,const sockaddr_storage&b){if(a.ss_family!=b.ss_family)return false;if(a.ss_family==AF_INET6){const auto*x=reinterpret_cast<const sockaddr_in6*>(&a),*y=reinterpret_cast<const sockaddr_in6*>(&b);return x->sin6_port==y->sin6_port&&std::memcmp(&x->sin6_addr,&y->sin6_addr,sizeof(in6_addr))==0;}if(a.ss_family==AF_INET){const auto*x=reinterpret_cast<const sockaddr_in*>(&a),*y=reinterpret_cast<const sockaddr_in*>(&b);return x->sin_port==y->sin_port&&x->sin_addr.s_addr==y->sin_addr.s_addr;}return false;}
}

struct PeerSession::Impl {
    PeerSessionOptions options;sockaddr_storage peer{};socklen_t peer_len=0;std::uint64_t session_numeric=0;
    PeerEphemeralKey ephemeral;PeerSessionKeys keys;std::unique_ptr<VideoCipher>cipher;ReplayWindow1024 replay;
    ReliableControlSender reliable_sender;ReliableControlReceiver reliable_receiver;LatestPointerReceiver pointer_receiver;
    std::thread thread;mutable std::mutex send_mu,state_mu,reliable_mu;std::atomic<bool>run{false},established{false};std::atomic<std::uint64_t>pointer_send_sequence{0},reliable_pending_count{0};std::uint64_t packet_send_sequence=1;std::string error;bool dropped_test_reliable=false;

    void set_error(std::string text){std::lock_guard<std::mutex>lock(state_mu);error=std::move(text);}
    bool resolve_peer(){return resolve_udp_endpoint(options.peer.host,options.peer.port,peer,peer_len);}
    bool send_wire(std::span<const std::uint8_t>wire){return send_datagram(options.socket.fd,peer,peer_len,wire);}
    bool send_plain(SessionPacketType type,std::string_view payload,std::uint64_t packet_sequence){SessionPacketHeader h;h.type=type;h.generation=options.handshake.generation;h.session_id=session_numeric;h.packet_sequence=packet_sequence;h.payload_length=static_cast<std::uint16_t>(payload.size());const auto header=serialize_session_header(h);if(header.empty()||payload.size()>kSessionPacketMaxPayload)return false;std::vector<std::uint8_t>wire=header;wire.insert(wire.end(),reinterpret_cast<const std::uint8_t*>(payload.data()),reinterpret_cast<const std::uint8_t*>(payload.data()+payload.size()));return send_wire(wire);}
    bool receive_wire(std::array<std::uint8_t,kSessionPacketMaxBytes+64>&buffer,std::span<const std::uint8_t>&wire,int timeout_ms){sockaddr_storage source{};socklen_t length=sizeof(source);const int n=recv_datagram(options.socket.fd,buffer,source,length,timeout_ms);if(n<=0)return false;if(!same_source(source,peer))return false;wire=std::span<const std::uint8_t>(buffer.data(),static_cast<std::size_t>(n));return true;}
    bool receive_plain(SessionPacketType expected,std::string&payload,int timeout_ms){const auto deadline=Clock::now()+std::chrono::milliseconds(std::max(1,timeout_ms));std::array<std::uint8_t,kSessionPacketMaxBytes+64>buffer{};while(remaining_ms(deadline)>0){std::span<const std::uint8_t>wire;if(!receive_wire(buffer,wire,remaining_ms(deadline)))continue;SessionPacketHeader h;if(!parse_session_header(wire,h)||h.type!=expected||h.generation!=options.handshake.generation||h.session_id!=session_numeric||wire.size()!=kSessionPacketHeaderBytes+h.payload_length)continue;payload.assign(reinterpret_cast<const char*>(wire.data()+kSessionPacketHeaderBytes),h.payload_length);return true;}return false;}
    bool install_keys(const std::string&client_ephemeral,const std::string&host_ephemeral){if(!derive_peer_session_keys(options.handshake,ephemeral,client_ephemeral,host_ephemeral,options.client_side,keys))return false;cipher=std::make_unique<VideoCipher>(video_keys(keys.control));replay.reset();return cipher&&cipher->valid();}
    bool client_handshake(std::string&err){
        if(!generate_peer_ephemeral(ephemeral)){err="ephemeral key generation failed";return false;}const auto client_ephemeral=peer_ephemeral_public_hex(ephemeral);const auto transcript=peer_client_hello_transcript(options.handshake,client_ephemeral);const auto signature=sign_hex(options.identity_private_key,transcript);if(signature.empty()){err="client identity signing failed";return false;}const std::string proof=options.handshake.auth_binding=="pairing"?peer_pairing_proof(options.pairing_password,options.handshake,client_ephemeral):"-";if(options.handshake.auth_binding=="pairing"&&proof.empty()){err="pairing proof unavailable";return false;}const std::string hello="HELLO "+options.handshake.client_identity+" "+client_ephemeral+" "+signature+" "+proof;
        const auto deadline=Clock::now()+std::chrono::milliseconds(std::max(1,options.handshake_timeout_ms));std::uint64_t handshake_sequence=1;std::array<std::uint8_t,kSessionPacketMaxBytes+64>buffer{};auto next_send=Clock::time_point{};
        while(remaining_ms(deadline)>0){const auto now=Clock::now();if(next_send.time_since_epoch().count()==0||now>=next_send){if(!send_plain(SessionPacketType::HandshakeClient,hello,handshake_sequence++)){err="client hello send failed";return false;}next_send=now+std::chrono::milliseconds(100);}std::span<const std::uint8_t>wire;if(!receive_wire(buffer,wire,std::min(50,remaining_ms(deadline))))continue;SessionPacketHeader h;if(!parse_session_header(wire,h)||h.generation!=options.handshake.generation||h.session_id!=session_numeric)continue;if(h.type!=SessionPacketType::HandshakeHost||wire.size()!=kSessionPacketHeaderBytes+h.payload_length)continue;const std::string payload(reinterpret_cast<const char*>(wire.data()+kSessionPacketHeaderBytes),h.payload_length);const auto f=fields(payload);if(f.size()!=5||f[0]!="WELCOME"||f[1]!=options.handshake.host_identity){err="host identity mismatch";return false;}const auto welcome=peer_host_welcome_transcript(options.handshake,client_ephemeral,f[2]);if(welcome.empty()||!verify_hex(options.handshake.host_identity,welcome,f[3])){err="host handshake signature invalid";return false;}if(!install_keys(client_ephemeral,f[2])){err="peer key derivation failed";return false;}if(peer_confirmation_mac(keys,welcome)!=f[4]){err="host key confirmation failed";return false;}const auto finish=peer_confirmation_mac(keys,"CLIENT\n"+welcome);if(finish.empty()){err="client key confirmation failed";return false;}for(int attempt=0;attempt<5&&remaining_ms(deadline)>0;++attempt){if(!send_plain(SessionPacketType::HandshakeFinish,"FINISH "+finish,handshake_sequence++)){err="client finish send failed";return false;}const auto wait_until=Clock::now()+std::chrono::milliseconds(150);while(Clock::now()<wait_until&&remaining_ms(deadline)>0){std::span<const std::uint8_t>reply;if(!receive_wire(buffer,reply,std::min(50,remaining_ms(deadline))))continue;if(open_encrypted(reply,nullptr,nullptr,SessionPacketType::Keepalive)){established.store(true,std::memory_order_release);return true;}}}err="host finish confirmation timed out";return false;}
    bool host_handshake(std::string&err){
        if(!generate_peer_ephemeral(ephemeral)){err="ephemeral key generation failed";return false;}const auto host_ephemeral=peer_ephemeral_public_hex(ephemeral);const auto deadline=Clock::now()+std::chrono::milliseconds(std::max(1,options.handshake_timeout_ms));std::array<std::uint8_t,kSessionPacketMaxBytes+64>buffer{};std::string client_ephemeral,welcome,welcome_payload;
        while(remaining_ms(deadline)>0){std::span<const std::uint8_t>wire;if(!receive_wire(buffer,wire,std::min(100,remaining_ms(deadline))))continue;SessionPacketHeader h;if(!parse_session_header(wire,h)||h.generation!=options.handshake.generation||h.session_id!=session_numeric||wire.size()!=kSessionPacketHeaderBytes+h.payload_length)continue;const std::string payload(reinterpret_cast<const char*>(wire.data()+kSessionPacketHeaderBytes),h.payload_length);
            if(h.type==SessionPacketType::HandshakeClient){const auto f=fields(payload);if(f.size()!=5||f[0]!="HELLO"||f[1]!=options.handshake.client_identity)continue;client_ephemeral=f[2];const auto hello=peer_client_hello_transcript(options.handshake,client_ephemeral);if(hello.empty()||!verify_hex(options.handshake.client_identity,hello,f[3]))continue;if(options.handshake.auth_binding=="pairing"){const auto expected=peer_pairing_proof(options.pairing_password,options.handshake,client_ephemeral);if(expected.empty()||f[4]!=expected)continue;}else if(f[4]!="-")continue;if(!install_keys(client_ephemeral,host_ephemeral)){err="peer key derivation failed";return false;}welcome=peer_host_welcome_transcript(options.handshake,client_ephemeral,host_ephemeral);const auto host_signature=sign_hex(options.identity_private_key,welcome);const auto confirmation=peer_confirmation_mac(keys,welcome);if(host_signature.empty()||confirmation.empty()){err="host handshake signing failed";return false;}welcome_payload="WELCOME "+options.handshake.host_identity+" "+host_ephemeral+" "+host_signature+" "+confirmation;if(!send_plain(SessionPacketType::HandshakeHost,welcome_payload,1)){err="host welcome send failed";return false;}continue;}
            if(h.type==SessionPacketType::HandshakeFinish&&!welcome.empty()){const auto f=fields(payload);if(f.size()!=2||f[0]!="FINISH"||f[1]!=peer_confirmation_mac(keys,"CLIENT\n"+welcome))continue;established.store(true,std::memory_order_release);if(!send_encrypted(SessionPacketType::Keepalive,0,"")){err="host confirmation send failed";return false;}return true;}
        }err="peer handshake timed out";return false;}
    bool send_encrypted(SessionPacketType type,std::uint64_t reliable_sequence,std::string_view payload){
        if(!cipher||payload.size()>kSessionPacketMaxPayload)return false;std::lock_guard<std::mutex>send_lock(send_mu);ReliableAckState ack;{std::lock_guard<std::mutex>lock(reliable_mu);ack=reliable_receiver.ack_state();}SessionPacketHeader h;h.type=type;h.generation=options.handshake.generation;h.session_id=session_numeric;h.packet_sequence=packet_send_sequence++;h.reliable_sequence=reliable_sequence;h.ack_sequence=ack.sequence;h.ack_bits=ack.bits;h.payload_length=static_cast<std::uint16_t>(payload.size());const auto aad=serialize_session_header(h);if(aad.empty())return false;std::vector<std::uint8_t>sealed(payload.size()+16);std::size_t sealed_size=0;if(!cipher->seal(h.packet_sequence,aad,std::span<const std::uint8_t>(reinterpret_cast<const std::uint8_t*>(payload.data()),payload.size()),sealed,sealed_size))return false;sealed.resize(sealed_size);std::vector<std::uint8_t>wire=aad;wire.insert(wire.end(),sealed.begin(),sealed.end());if(type==SessionPacketType::ReliableControl){const char*drop=std::getenv("OPAL_TEST_DROP_FIRST_RELIABLE");if(drop&&*drop&&std::string(drop)!="0"&&!dropped_test_reliable){dropped_test_reliable=true;return true;}}return send_wire(wire);}
    bool open_encrypted(std::span<const std::uint8_t>wire,SessionPacketHeader*out_header,std::string*out_payload,SessionPacketType require=static_cast<SessionPacketType>(0)){
        if(!cipher||wire.size()<kSessionPacketHeaderBytes+16)return false;SessionPacketHeader h;if(!parse_session_header(wire,h)||h.generation!=options.handshake.generation||h.session_id!=session_numeric||wire.size()!=kSessionPacketHeaderBytes+h.payload_length+16)return false;if(static_cast<std::uint8_t>(require)!=0&&h.type!=require)return false;std::vector<std::uint8_t>plain(h.payload_length);std::size_t plain_size=0;if(!cipher->open(h.packet_sequence,wire.first(kSessionPacketHeaderBytes),wire.subspan(kSessionPacketHeaderBytes),plain,plain_size)||plain_size!=h.payload_length)return false;if(!replay.accept(h.packet_sequence))return false;if(out_header)*out_header=h;if(out_payload)out_payload->assign(reinterpret_cast<const char*>(plain.data()),plain.size());return true;}
    void process_encrypted(std::span<const std::uint8_t>wire){SessionPacketHeader h;std::string payload;if(!open_encrypted(wire,&h,&payload))return;{std::lock_guard<std::mutex>lock(reliable_mu);reliable_sender.acknowledge({h.ack_sequence,h.ack_bits});reliable_pending_count.store(reliable_sender.pending(),std::memory_order_relaxed);}if(h.type==SessionPacketType::ReliableControl){std::vector<std::string>delivered;{std::lock_guard<std::mutex>lock(reliable_mu);reliable_receiver.receive(h.reliable_sequence,std::move(payload),delivered);}for(const auto&command:delivered)if(options.reliable_input)options.reliable_input(command);(void)send_encrypted(SessionPacketType::ControlAck,0,"");return;}if(h.type==SessionPacketType::Pointer){bool accepted=false;{std::lock_guard<std::mutex>lock(reliable_mu);accepted=pointer_receiver.accept(h.reliable_sequence,std::move(payload));}if(accepted&&options.pointer_input)options.pointer_input(pointer_receiver.latest());return;}}
    void loop(){auto next_keepalive=Clock::now()+std::chrono::milliseconds(500);auto last_authenticated=Clock::now();std::array<std::uint8_t,kSessionPacketMaxBytes+256>buffer{};while(run.load()){sockaddr_storage source{};socklen_t source_len=sizeof(source);const int n=recv_datagram(options.socket.fd,buffer,source,source_len,10);if(n>0&&same_source(source,peer)){const std::span<const std::uint8_t>wire(buffer.data(),static_cast<std::size_t>(n));if(read_magic(wire)==kSessionPacketMagic){SessionPacketHeader h;std::string payload;if(open_encrypted(wire,&h,&payload)){last_authenticated=Clock::now();{std::lock_guard<std::mutex>lock(reliable_mu);reliable_sender.acknowledge({h.ack_sequence,h.ack_bits});reliable_pending_count.store(reliable_sender.pending(),std::memory_order_relaxed);}if(h.type==SessionPacketType::ReliableControl){std::vector<std::string>delivered;{std::lock_guard<std::mutex>lock(reliable_mu);reliable_receiver.receive(h.reliable_sequence,std::move(payload),delivered);}for(const auto&command:delivered)if(options.reliable_input)options.reliable_input(command);(void)send_encrypted(SessionPacketType::ControlAck,0,"");}else if(h.type==SessionPacketType::Pointer){bool accepted=false;std::string latest;{std::lock_guard<std::mutex>lock(reliable_mu);accepted=pointer_receiver.accept(h.reliable_sequence,std::move(payload));if(accepted)latest=pointer_receiver.latest();}if(accepted&&options.pointer_input)options.pointer_input(latest);}}}else if(options.media_datagram)options.media_datagram(wire);}
            const auto now=monotonic_ms();std::vector<ReliableTransmission>due;{std::lock_guard<std::mutex>lock(reliable_mu);due=reliable_sender.due(now);reliable_pending_count.store(reliable_sender.pending(),std::memory_order_relaxed);if(reliable_sender.failed()){set_error("reliable control timed out");run.store(false);break;}}for(const auto&tx:due)if(!send_encrypted(SessionPacketType::ReliableControl,tx.sequence,tx.payload)){set_error("control send failed");run.store(false);break;}const auto steady=Clock::now();if(steady>=next_keepalive){(void)send_encrypted(SessionPacketType::Keepalive,0,"");next_keepalive=steady+std::chrono::milliseconds(500);}if(steady-last_authenticated>std::chrono::seconds(5)){set_error("peer session timed out");run.store(false);break;}}
        established.store(false,std::memory_order_release);}
};

PeerSession::PeerSession():impl_(std::make_unique<Impl>()){}
PeerSession::~PeerSession(){stop();}

bool PeerSession::start(PeerSessionOptions options,std::string&error){stop();impl_=std::make_unique<Impl>();impl_->options=std::move(options);impl_->session_numeric=numeric_session_id(impl_->options.handshake.session_id);if(impl_->options.socket.fd<0||impl_->options.peer.host.empty()||impl_->options.peer.port==0||impl_->session_numeric==0||impl_->options.handshake.generation==0||!impl_->resolve_peer()){error="invalid peer session options";return false;}std::string handshake_error;const bool ok=impl_->options.client_side?impl_->client_handshake(handshake_error):impl_->host_handshake(handshake_error);if(!ok){impl_->set_error(handshake_error);error=handshake_error;clear_peer_ephemeral(impl_->ephemeral);clear_peer_session_keys(impl_->keys);return false;}clear_peer_ephemeral(impl_->ephemeral);impl_->run.store(true);impl_->thread=std::thread([this]{impl_->loop();});error.clear();return true;}

bool PeerSession::send_input(std::string command){if(command.rfind("POINTER ",0)==0)return send_pointer(std::move(command));if(!impl_||!impl_->run.load())return false;std::lock_guard<std::mutex>lock(impl_->reliable_mu);const auto sequence=impl_->reliable_sender.enqueue(std::move(command),monotonic_ms());impl_->reliable_pending_count.store(impl_->reliable_sender.pending(),std::memory_order_relaxed);return sequence!=0;}
bool PeerSession::send_pointer(std::string command){if(!impl_||!impl_->run.load()||command.rfind("POINTER ",0)!=0)return false;const auto sequence=impl_->pointer_send_sequence.fetch_add(1,std::memory_order_relaxed)+1;return impl_->send_encrypted(SessionPacketType::Pointer,sequence,command);}
bool PeerSession::send_media_datagram(std::span<const std::uint8_t>wire){return impl_&&impl_->run.load()&&!wire.empty()&&wire.size()<=kVideoMaxDatagramBytes&&impl_->send_wire(wire);}
bool PeerSession::established()const{return impl_&&impl_->established.load(std::memory_order_acquire);}
bool PeerSession::running()const{return impl_&&impl_->run.load();}
std::uint32_t PeerSession::generation()const{return impl_?impl_->options.handshake.generation:0;}
std::uint16_t PeerSession::local_port()const{return impl_?impl_->options.socket.local_port:0;}
std::uint64_t PeerSession::reliable_pending()const{return impl_?impl_->reliable_pending_count.load():0;}
std::uint64_t PeerSession::pointer_sequence()const{return impl_?impl_->pointer_send_sequence.load():0;}
std::string PeerSession::last_error()const{if(!impl_)return{};std::lock_guard<std::mutex>lock(impl_->state_mu);return impl_->error;}
void PeerSession::stop(){if(!impl_)return;impl_->run.store(false);if(impl_->options.socket.fd>=0)shutdown(impl_->options.socket.fd,SHUT_RDWR);if(impl_->thread.joinable())impl_->thread.join();close_udp_socket(impl_->options.socket);impl_->established.store(false);impl_->cipher.reset();clear_peer_ephemeral(impl_->ephemeral);clear_peer_session_keys(impl_->keys);}

}
