#include <opal/session.hpp>
#include <opal/crypto.hpp>
#include <opal/media.hpp>
#include <opal/net.hpp>
#include <opal/tunnel_access.hpp>
#include <algorithm>
#include <atomic>
#include <cctype>
#include <chrono>
#include <condition_variable>
#include <cstdlib>
#include <deque>
#include <filesystem>
#include <iostream>
#include <mutex>
#include <poll.h>
#include <signal.h>
#include <sstream>
#include <sys/socket.h>
#include <thread>
#include <unistd.h>

namespace opal { namespace {
using namespace std::chrono_literals;
bool debug_enabled(){const char*v=std::getenv("OPAL_DEBUG");if(!v||!*v)return false;std::string x=v;return x!="0"&&x!="false"&&x!="FALSE"&&x!="off"&&x!="OFF";}
std::string player_command(){if(const char*e=std::getenv("OPAL_PLAYER_CMD");e&&*e)return e;std::string cmd=debug_enabled()?"ffplay -hide_banner -loglevel warning -fflags nobuffer -flags low_delay -avioflags direct -probesize 32 -analyzeduration 0 -sync video -framedrop -fs -autoexit -i pipe:0":"ffplay -hide_banner -loglevel quiet -fflags nobuffer -flags low_delay -avioflags direct -probesize 32 -analyzeduration 0 -sync video -framedrop -fs -autoexit -i pipe:0 >/dev/null 2>&1";if(const char*display=std::getenv("DISPLAY");display&&*display)cmd="SDL_VIDEODRIVER=x11 "+cmd;return cmd;}
bool wait_for_input(int fd,int timeout_ms){pollfd p{fd,POLLIN,0};for(;;){int rc=poll(&p,1,timeout_ms);if(rc<0&&errno==EINTR)continue;if(rc<=0)return false;if(p.revents&(POLLERR|POLLHUP|POLLNVAL))return false;return(p.revents&POLLIN)!=0;}}
bool pointer_command(const std::string&s){return s.rfind("POINTER ",0)==0;}
bool valid_mac(const std::string&s){if(s.size()!=17)return false;for(size_t i=0;i<s.size();++i){if((i+1)%3==0){if(s[i]!=':')return false;}else if(!std::isxdigit(static_cast<unsigned char>(s[i])))return false;}return true;}
}

struct SessionSupervisor::Impl {
    explicit Impl(SessionOptions o):options(std::move(o)),paired_state(options.paired){}
    SessionOptions options;SSL_CTX*ctx=nullptr;TlsConn control;TunnelAccessHandle tunnel;
    std::mutex control_mu,recovery_mu,queue_mu;mutable std::mutex state_mu;std::condition_variable state_cv,queue_cv;
    std::thread control_thread,video_thread;std::deque<std::string> outbound;
    std::atomic<bool> run{false},media{false},paired_state{false};std::atomic<unsigned long> generation{0};std::atomic<int> control_fd{-1},video_fd{-1};
    std::string current_video_token,observed_fingerprint,remote_mac_value,error;int remote_width_value=0,remote_height_value=0;

    void set_error(const std::string&m){std::lock_guard<std::mutex>l(state_mu);error=m;}
    bool ensure_tunnel(){if(!options.tunneled)return true;if(tunnel_access_healthy(tunnel)){options.control_port=tunnel.control_port;options.video_port=tunnel.video_port;return true;}if(!tunnel_access_start(tunnel,options.control_token,options.video_token,30000)){set_error("OPAL tunnel access failed");return false;}options.control_port=tunnel.control_port;options.video_port=tunnel.video_port;return true;}
    bool verify_fingerprint(TlsConn&c,std::string&fp){fp=peer_fingerprint(c.ssl);std::string expected;{std::lock_guard<std::mutex>l(state_mu);expected=!options.fingerprint.empty()?options.fingerprint:observed_fingerprint;}if(fp.empty()||(!expected.empty()&&!secure_equal(expected,fp))){set_error(expected.empty()?"host certificate unavailable":"host certificate changed; refusing connection");return false;}return true;}
    bool authenticate(TlsConn&c,bool allow_pair,std::string&token,std::string&fp){if(!verify_fingerprint(c,fp))return false;std::string challenge;if(!tls_read_line_timeout(c.ssl,challenge,5000)||challenge.rfind("CHALLENGE ",0)!=0){set_error("control authentication challenge failed");return false;}auto payload=challenge.substr(10);if(payload.rfind("OPAL2 ",0)!=0){set_error("incompatible OPAL host protocol; update OPAL on both computers");return false;}auto nonce=payload.substr(6);int pw=0,ph=0;std::string pmac;{std::istringstream m(nonce);std::string random,mac,extra;int w=0,h=0;if(m>>random>>w>>h){if(w>0&&h>0){pw=w;ph=h;}if(m>>mac){if(!(m>>extra)&&valid_mac(mac))pmac=mac;else{pw=0;ph=0;pmac.clear();}}}}
        std::string auth;if(paired_state.load()){if(options.client_public_key.empty()||options.client_private_key_path.empty()){set_error("saved client identity unavailable");return false;}auto sig=sign_hex(std::filesystem::path(options.client_private_key_path),nonce);if(sig.empty()){set_error("client authentication signature failed");return false;}auth="AUTH "+options.client_public_key+" "+sig;}else{if(!allow_pair){set_error("paired recovery cannot fall back to pairing");return false;}std::string password=options.pairing_password;if(password.empty()&&options.pairing_password_provider)password=options.pairing_password_provider();password=normalize_pairing_code(password);if(password.empty()){set_error("pairing password required");return false;}auto transcript="OPAL-PAIR-v2\n"+fp+"\n"+nonce+"\n"+options.client_public_key;auth="PAIR "+options.client_public_key+" "+hmac_sha256_hex(password,transcript);if(!options.label.empty())auth+=" "+options.label;}
        if(!tls_write_line_timeout(c.ssl,auth,2000)){set_error("control authentication write failed");return false;}std::string reply;if(!tls_read_line_timeout(c.ssl,reply,5000)){set_error("control authentication reply failed");return false;}if(reply.rfind("OK ",0)!=0){set_error(paired_state.load()?"saved client authentication denied":"pairing password incorrect or expired");return false;}token=reply.substr(3);if(token.empty()){set_error("host returned an empty video token");return false;}if((pw>0&&ph>0)||!pmac.empty()){std::lock_guard<std::mutex>l(state_mu);if(pw>0&&ph>0){remote_width_value=pw;remote_height_value=ph;}if(!pmac.empty())remote_mac_value=pmac;}paired_state.store(true);return true;}
    bool connect_authenticated(bool allow_pair,TlsConn&out,std::string&token,std::string&fp){auto c=connect_tls_retry(ctx,options.target,static_cast<uint16_t>(options.control_port),10000,100);if(!c.ssl){set_error("cannot connect to OPAL host");return false;}if(!authenticate(c,allow_pair,token,fp)){close_tls(c);return false;}out=c;c={};return true;}
    void install_control(TlsConn&next,const std::string&token,const std::string&fp,bool first){{std::lock_guard<std::mutex>l(control_mu);close_tls(control);control=next;next={};control_fd.store(control.fd);} {std::lock_guard<std::mutex>l(state_mu);current_video_token=token;if(observed_fingerprint.empty())observed_fingerprint=fp;if(options.fingerprint.empty())options.fingerprint=observed_fingerprint;error.clear();}if(first)generation.store(1);else generation.fetch_add(1);state_cv.notify_all();}
    void interrupt_video(){int fd=video_fd.load();if(fd>=0)shutdown(fd,SHUT_RDWR);}
    void clear_queue(){std::lock_guard<std::mutex>l(queue_mu);outbound.clear();}
    bool recover_control(unsigned long failed){std::lock_guard<std::mutex>r(recovery_mu);if(!run.load())return false;if(generation.load()!=failed)return true;interrupt_video();int fd=control_fd.exchange(-1);if(fd>=0)shutdown(fd,SHUT_RDWR);{std::lock_guard<std::mutex>l(control_mu);close_tls(control);}clear_queue();std::cout<<"Control interrupted; recovering...\n"<<std::flush;if(!ensure_tunnel()){run.store(false);state_cv.notify_all();queue_cv.notify_all();return false;}TlsConn next;std::string token,fp;if(!paired_state.load()||!connect_authenticated(false,next,token,fp)){if(!paired_state.load())set_error("control recovery requires a paired identity");run.store(false);state_cv.notify_all();queue_cv.notify_all();return false;}install_control(next,token,fp,false);std::cout<<"Control restored.\n"<<std::flush;return true;}
    bool send_control(const std::string&line,int timeout){std::lock_guard<std::mutex>l(control_mu);return control.ssl&&tls_write_line_timeout(control.ssl,line,timeout);}
    void control_loop(){auto next_ping=std::chrono::steady_clock::now()+2s;while(run.load()){std::string command;{std::unique_lock<std::mutex>l(queue_mu);queue_cv.wait_until(l,next_ping,[&]{return !run.load()||!outbound.empty();});if(!run.load())break;if(!outbound.empty()){command=std::move(outbound.front());outbound.pop_front();}}unsigned long g=generation.load();if(!command.empty()&&!send_control(command,250)){if(!recover_control(g))break;next_ping=std::chrono::steady_clock::now()+2s;continue;}if(std::chrono::steady_clock::now()>=next_ping){bool ok=false;{std::lock_guard<std::mutex>l(control_mu);if(control.ssl&&tls_write_line_timeout(control.ssl,"PING",500)){std::string pong;ok=tls_read_line_timeout(control.ssl,pong,1000)&&pong=="PONG";}}if(!ok&&!recover_control(g))break;next_ping=std::chrono::steady_clock::now()+2s;}}}
    bool open_video(TlsConn&v,const std::string&token){auto next=connect_tls_retry(ctx,options.target,static_cast<uint16_t>(options.video_port),5000,100);if(!next.ssl)return false;std::string fp=peer_fingerprint(next.ssl),expected;{std::lock_guard<std::mutex>l(state_mu);expected=observed_fingerprint;}if(!expected.empty()&&!secure_equal(expected,fp)){close_tls(next);set_error("video certificate changed; refusing connection");return false;}auto request=video_request_line(token,options.stream.max_width,options.stream.max_height,options.stream.fps);if(!tls_write_line_timeout(next.ssl,request,1000)){close_tls(next);return false;}std::string ready;if(!tls_read_line_timeout(next.ssl,ready,12000)||ready!="READY"){close_tls(next);return false;}v=next;next={};return true;}
    void video_loop(){bool recovering=false,first=true;unsigned long lastg=0;while(run.load()){std::string token;unsigned long g=0;{std::unique_lock<std::mutex>l(state_mu);state_cv.wait_for(l,200ms,[&]{return !run.load()||(!current_video_token.empty()&&generation.load()>0);});if(!run.load())break;token=current_video_token;g=generation.load();}if(token.empty())continue;if(first){std::cout<<"Video connecting...\n"<<std::flush;first=false;}TlsConn v;if(!open_video(v,token)){if(run.load())std::this_thread::sleep_for(150ms);continue;}video_fd.store(v.fd);auto player=start_sink(player_command());if(player.pid<=0||player.fd<0){video_fd.store(-1);close_tls(v);set_error("could not start video player");std::this_thread::sleep_for(150ms);continue;}if(recovering){std::cout<<"Video restored.\n"<<std::flush;recovering=false;}else if(!media.load())std::cout<<"Video connected.\n"<<std::flush;lastg=g;bool got=false,ok=true;while(run.load()&&generation.load()==g){if(SSL_pending(v.ssl)==0&&!wait_for_input(v.fd,3000)){ok=false;break;}char buf[65536];int n=SSL_read(v.ssl,buf,sizeof(buf));if(n<=0){ok=false;break;}if(!write_sink_timeout(player,buf,static_cast<size_t>(n),video_player_write_timeout_ms())){ok=false;break;}got=true;media.store(true);}video_fd.store(-1);shutdown(v.fd,SHUT_RDWR);close_tls(v);stop_sink(player);if(!run.load())break;if(got||!ok||generation.load()!=lastg){std::cout<<"Video interrupted; recovering...\nVideo stalled; reconnecting...\n"<<std::flush;recovering=true;}std::this_thread::sleep_for(75ms);}video_fd.store(-1);}
    bool start(){if(run.load())return true;signal(SIGPIPE,SIG_IGN);ctx=client_tls_context();if(!ctx){set_error("cannot create client TLS context");return false;}run.store(true);media.store(false);generation.store(0);if(!ensure_tunnel()){run.store(false);SSL_CTX_free(ctx);ctx=nullptr;return false;}TlsConn initial;std::string token,fp;if(!connect_authenticated(true,initial,token,fp)){run.store(false);tunnel_access_stop(tunnel);SSL_CTX_free(ctx);ctx=nullptr;return false;}install_control(initial,token,fp,true);control_thread=std::thread([this]{control_loop();});video_thread=std::thread([this]{video_loop();});return true;}
    void stop(){bool was=run.exchange(false);state_cv.notify_all();queue_cv.notify_all();interrupt_video();int fd=control_fd.exchange(-1);if(fd>=0)shutdown(fd,SHUT_RDWR);if(control_thread.joinable())control_thread.join();if(video_thread.joinable())video_thread.join();{std::lock_guard<std::mutex>l(control_mu);close_tls(control);}tunnel_access_stop(tunnel);if(ctx){SSL_CTX_free(ctx);ctx=nullptr;}if(!was)return;}
    bool enqueue(std::string command){if(command.empty())return true;if(!run.load())return false;std::lock_guard<std::mutex>l(queue_mu);if(pointer_command(command)&&!outbound.empty()&&pointer_command(outbound.back())){outbound.back()=std::move(command);queue_cv.notify_one();return true;}if(outbound.size()>=1024){auto it=std::find_if(outbound.begin(),outbound.end(),[](const std::string&s){return pointer_command(s);});if(it!=outbound.end())outbound.erase(it);else{set_error("control queue overflow");run.store(false);int fd=control_fd.load();if(fd>=0)shutdown(fd,SHUT_RDWR);interrupt_video();state_cv.notify_all();queue_cv.notify_all();return false;}}outbound.push_back(std::move(command));queue_cv.notify_one();return true;}
};

SessionSupervisor::SessionSupervisor(SessionOptions o):impl_(std::make_unique<Impl>(std::move(o))){}
SessionSupervisor::~SessionSupervisor(){impl_->stop();}
bool SessionSupervisor::start(){return impl_->start();}void SessionSupervisor::stop(){impl_->stop();}
bool SessionSupervisor::send_input(const std::string&c){return impl_->enqueue(c);}unsigned long SessionSupervisor::control_generation()const{return impl_->generation.load();}bool SessionSupervisor::media_started()const{return impl_->media.load();}bool SessionSupervisor::running()const{return impl_->run.load();}bool SessionSupervisor::paired()const{return impl_->paired_state.load();}
int SessionSupervisor::remote_width()const{std::lock_guard<std::mutex>l(impl_->state_mu);return impl_->remote_width_value;}int SessionSupervisor::remote_height()const{std::lock_guard<std::mutex>l(impl_->state_mu);return impl_->remote_height_value;}std::string SessionSupervisor::remote_mac()const{std::lock_guard<std::mutex>l(impl_->state_mu);return impl_->remote_mac_value;}std::string SessionSupervisor::fingerprint()const{std::lock_guard<std::mutex>l(impl_->state_mu);return impl_->observed_fingerprint;}std::string SessionSupervisor::last_error()const{std::lock_guard<std::mutex>l(impl_->state_mu);return impl_->error;}
}
