#define GL_GLEXT_PROTOTYPES 1
#include <opal/video_present.hpp>
#include <opal/latency_window.hpp>

#include <SDL3/SDL.h>
#include <GL/gl.h>
#include <algorithm>
#include <array>
#include <chrono>
#include <cstddef>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <string>
#include <vector>

extern "C" {
#include <libavutil/hwcontext.h>
#include <libavutil/pixfmt.h>
}

#if __has_include(<EGL/egl.h>) && __has_include(<EGL/eglext.h>) && __has_include(<libavutil/hwcontext_drm.h>) && __has_include(<libdrm/drm_fourcc.h>)
#define OPAL_HAVE_DRM_PRIME_EGL 1
#include <EGL/egl.h>
#include <EGL/eglext.h>
#include <libdrm/drm_fourcc.h>
extern "C" {
#include <libavutil/hwcontext_drm.h>
}
#else
#define OPAL_HAVE_DRM_PRIME_EGL 0
#endif

namespace opal {
namespace {
using Clock=std::chrono::steady_clock;
bool debug_enabled(){const char*v=std::getenv("OPAL_DEBUG");return v&&*v&&std::string(v)!="0";}
bool env_enabled(const char*name){const char*v=std::getenv(name);return v&&*v&&std::string(v)!="0";}
std::string env_value(const char*name){const char*v=std::getenv(name);return v&&*v?std::string(v):std::string{};}
double elapsed_ms(Clock::time_point begin,Clock::time_point end){return std::chrono::duration<double,std::milli>(end-begin).count();}
GLuint compile_shader(GLenum type,const char*source){GLuint shader=glCreateShader(type);if(!shader)return 0;glShaderSource(shader,1,&source,nullptr);glCompileShader(shader);GLint ok=GL_FALSE;glGetShaderiv(shader,GL_COMPILE_STATUS,&ok);if(!ok){glDeleteShader(shader);return 0;}return shader;}
GLuint make_program(){static const char*vertex=R"GLSL(#version 120
varying vec2 uv;void main(){gl_Position=gl_Vertex;uv=gl_MultiTexCoord0.xy;})GLSL";static const char*fragment=R"GLSL(#version 120
uniform sampler2D tex_y;uniform sampler2D tex_u;uniform sampler2D tex_v;uniform sampler2D tex_uv;uniform int nv12;varying vec2 uv;void main(){float y=texture2D(tex_y,uv).r;float u;float v;if(nv12!=0){vec4 c=texture2D(tex_uv,uv);u=c.r-0.5;v=(nv12==2?c.g:c.a)-0.5;}else{u=texture2D(tex_u,uv).r-0.5;v=texture2D(tex_v,uv).r-0.5;}y=max(0.0,1.1643*(y-0.0625));gl_FragColor=vec4(y+1.5958*v,y-0.39173*u-0.81290*v,y+2.017*u,1.0);})GLSL";GLuint vs=compile_shader(GL_VERTEX_SHADER,vertex),fs=compile_shader(GL_FRAGMENT_SHADER,fragment);if(!vs||!fs){if(vs)glDeleteShader(vs);if(fs)glDeleteShader(fs);return 0;}GLuint program=glCreateProgram();if(!program){glDeleteShader(vs);glDeleteShader(fs);return 0;}glAttachShader(program,vs);glAttachShader(program,fs);glLinkProgram(program);glDeleteShader(vs);glDeleteShader(fs);GLint ok=GL_FALSE;glGetProgramiv(program,GL_LINK_STATUS,&ok);if(!ok){glDeleteProgram(program);return 0;}return program;}
const void*upload_source(const std::uint8_t*src,int stride,int width,int height,int bpp,std::vector<std::uint8_t>&scratch,int&row_length){row_length=0;if(!src||width<=0||height<=0||bpp<=0)return nullptr;const int row_bytes=width*bpp;if(stride>0&&stride>=row_bytes&&stride%bpp==0){row_length=stride/bpp;return src;}scratch.resize(static_cast<std::size_t>(row_bytes)*height);for(int y=0;y<height;++y)std::memcpy(scratch.data()+static_cast<std::size_t>(y)*row_bytes,src+static_cast<std::ptrdiff_t>(y)*stride,row_bytes);return scratch.data();}
void upload_plane_direct(GLenum unit,GLuint texture,GLenum format,int width,int height,const std::uint8_t*src,int stride,int bpp,std::vector<std::uint8_t>&scratch){int row_length=0;const void*pixels=upload_source(src,stride,width,height,bpp,scratch,row_length);if(!pixels)return;glBindBuffer(GL_PIXEL_UNPACK_BUFFER,0);glActiveTexture(unit);glBindTexture(GL_TEXTURE_2D,texture);glPixelStorei(GL_UNPACK_ROW_LENGTH,row_length);glTexSubImage2D(GL_TEXTURE_2D,0,0,0,width,height,format,GL_UNSIGNED_BYTE,pixels);glPixelStorei(GL_UNPACK_ROW_LENGTH,0);}
void fitted_viewport(int ww,int wh,int sw,int sh){ww=std::max(1,ww);wh=std::max(1,wh);sw=std::max(1,sw);sh=std::max(1,sh);const long long lhs=static_cast<long long>(ww)*sh,rhs=static_cast<long long>(wh)*sw;int w=ww,h=wh,x=0,y=0;if(lhs>rhs){w=std::max(1,static_cast<int>(static_cast<long long>(wh)*sw/sh));x=(ww-w)/2;}else if(lhs<rhs){h=std::max(1,static_cast<int>(static_cast<long long>(ww)*sh/sw));y=(wh-h)/2;}glViewport(x,y,w,h);}
SDL_FRect fitted_rect(int ww,int wh,int sw,int sh){ww=std::max(1,ww);wh=std::max(1,wh);sw=std::max(1,sw);sh=std::max(1,sh);const double source=static_cast<double>(sw)/static_cast<double>(sh),window=static_cast<double>(ww)/static_cast<double>(wh);float w=static_cast<float>(ww),h=static_cast<float>(wh);if(window>source)w=static_cast<float>(static_cast<double>(wh)*source);else if(window<source)h=static_cast<float>(static_cast<double>(ww)/source);return SDL_FRect{(static_cast<float>(ww)-w)*0.5f,(static_cast<float>(wh)-h)*0.5f,w,h};}
}

struct VideoPresenter::Impl{
    SDL_Window*window=nullptr;
    SDL_Renderer*renderer=nullptr;
    SDL_Texture*render_texture=nullptr;
    std::string renderer_name;
    int renderer_format=AV_PIX_FMT_NONE,renderer_width=0,renderer_height=0;
    bool renderer_active=false;

    SDL_GLContext context=nullptr;GLuint program=0;GLint nv12_uniform=-1;std::array<GLuint,4>textures{};std::array<GLuint,8>unpack_buffers{};int texture_width=0,texture_height=0,drawable_width=0,drawable_height=0;std::uint64_t presented=0,last_size_refresh=0;std::size_t pbo_phase=0;bool pbo_ready=false,immediate_swap=false,drm_import_ready=false,drm_import_active=false;std::vector<std::uint8_t>scratch_y,scratch_u,scratch_v,scratch_uv;LatencyWindow<128>upload_latency,swap_latency;Clock::time_point last_debug{};
#if OPAL_HAVE_DRM_PRIME_EGL
    using ImageTargetProc=void(*)(GLenum,void*);
    EGLDisplay egl_display=EGL_NO_DISPLAY;PFNEGLCREATEIMAGEKHRPROC egl_create_image=nullptr;PFNEGLDESTROYIMAGEKHRPROC egl_destroy_image=nullptr;PFNEGLQUERYSTRINGPROC egl_query_string=nullptr;ImageTargetProc image_target=nullptr;bool drm_modifiers=false;
#endif
    bool refresh_drawable_size(bool force=false){if(!window)return false;if(!force&&drawable_width>0&&drawable_height>0&&presented-last_size_refresh<8)return true;int w=0,h=0;if(!SDL_GetWindowSizeInPixels(window,&w,&h)||w<=0||h<=0)return drawable_width>0&&drawable_height>0;drawable_width=w;drawable_height=h;last_size_refresh=presented;return true;}
    bool init_renderer(){renderer=SDL_CreateRenderer(window,"gpu,vulkan,opengl,opengles2");if(!renderer)return false;const char*name=SDL_GetRendererName(renderer);renderer_name=name&&*name?name:"unknown";if(renderer_name=="software"){SDL_DestroyRenderer(renderer);renderer=nullptr;return false;}(void)SDL_SetRenderVSync(renderer,SDL_RENDERER_VSYNC_DISABLED);int vsync=1;immediate_swap=SDL_GetRenderVSync(renderer,&vsync)&&vsync==SDL_RENDERER_VSYNC_DISABLED;(void)SDL_SetRenderDrawColor(renderer,0,0,0,255);renderer_active=true;return true;}
    bool ensure_renderer_texture(int width,int height,int format){if(!renderer||width<=0||height<=0)return false;if(render_texture&&renderer_width==width&&renderer_height==height&&renderer_format==format)return true;if(render_texture){SDL_DestroyTexture(render_texture);render_texture=nullptr;}SDL_PixelFormat pixel_format=SDL_PIXELFORMAT_UNKNOWN;SDL_Colorspace colorspace=SDL_COLORSPACE_BT709_LIMITED;if(format==AV_PIX_FMT_YUV420P){pixel_format=SDL_PIXELFORMAT_IYUV;colorspace=SDL_COLORSPACE_BT709_LIMITED;}else if(format==AV_PIX_FMT_YUVJ420P){pixel_format=SDL_PIXELFORMAT_IYUV;colorspace=SDL_COLORSPACE_BT709_FULL;}else if(format==AV_PIX_FMT_NV12){pixel_format=SDL_PIXELFORMAT_NV12;colorspace=SDL_COLORSPACE_BT709_LIMITED;}else return false;const SDL_PropertiesID props=SDL_CreateProperties();if(!props)return false;const bool props_ok=SDL_SetNumberProperty(props,SDL_PROP_TEXTURE_CREATE_FORMAT_NUMBER,static_cast<Sint64>(pixel_format))&&SDL_SetNumberProperty(props,SDL_PROP_TEXTURE_CREATE_ACCESS_NUMBER,static_cast<Sint64>(SDL_TEXTUREACCESS_STREAMING))&&SDL_SetNumberProperty(props,SDL_PROP_TEXTURE_CREATE_WIDTH_NUMBER,width)&&SDL_SetNumberProperty(props,SDL_PROP_TEXTURE_CREATE_HEIGHT_NUMBER,height)&&SDL_SetNumberProperty(props,SDL_PROP_TEXTURE_CREATE_COLORSPACE_NUMBER,static_cast<Sint64>(colorspace));if(props_ok)render_texture=SDL_CreateTextureWithProperties(renderer,props);SDL_DestroyProperties(props);if(!render_texture)return false;(void)SDL_SetTextureScaleMode(render_texture,SDL_SCALEMODE_LINEAR);renderer_width=width;renderer_height=height;renderer_format=format;return true;}
    bool present_renderer(const AVFrame*f){if(!renderer_active||!renderer||!f||!ensure_renderer_texture(f->width,f->height,f->format)||!refresh_drawable_size())return false;const auto upload_begin=Clock::now();bool uploaded=false;if(f->format==AV_PIX_FMT_YUV420P||f->format==AV_PIX_FMT_YUVJ420P)uploaded=SDL_UpdateYUVTexture(render_texture,nullptr,f->data[0],f->linesize[0],f->data[1],f->linesize[1],f->data[2],f->linesize[2]);else if(f->format==AV_PIX_FMT_NV12)uploaded=SDL_UpdateNVTexture(render_texture,nullptr,f->data[0],f->linesize[0],f->data[1],f->linesize[1]);const auto upload_end=Clock::now();if(!uploaded)return false;upload_latency.push(elapsed_ms(upload_begin,upload_end));const SDL_FRect dst=fitted_rect(drawable_width,drawable_height,f->width,f->height);const auto present_begin=Clock::now();if(!SDL_RenderClear(renderer)||!SDL_RenderTexture(renderer,render_texture,nullptr,&dst)||!SDL_RenderPresent(renderer))return false;const auto present_end=Clock::now();swap_latency.push(elapsed_ms(present_begin,present_end));++presented;debug_timing();return true;}
    bool init_gl(){program=make_program();if(!program)return false;glGenTextures(static_cast<GLsizei>(textures.size()),textures.data());for(GLuint t:textures){glBindTexture(GL_TEXTURE_2D,t);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_CLAMP_TO_EDGE);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE);}if(env_enabled("OPAL_PBO")){glGenBuffers(static_cast<GLsizei>(unpack_buffers.size()),unpack_buffers.data());pbo_ready=std::all_of(unpack_buffers.begin(),unpack_buffers.end(),[](GLuint id){return id!=0;});}glBindBuffer(GL_PIXEL_UNPACK_BUFFER,0);glUseProgram(program);glUniform1i(glGetUniformLocation(program,"tex_y"),0);glUniform1i(glGetUniformLocation(program,"tex_u"),1);glUniform1i(glGetUniformLocation(program,"tex_v"),2);glUniform1i(glGetUniformLocation(program,"tex_uv"),3);nv12_uniform=glGetUniformLocation(program,"nv12");glUseProgram(0);
#if OPAL_HAVE_DRM_PRIME_EGL
        egl_display=reinterpret_cast<EGLDisplay>(SDL_EGL_GetCurrentDisplay());egl_create_image=reinterpret_cast<PFNEGLCREATEIMAGEKHRPROC>(SDL_EGL_GetProcAddress("eglCreateImageKHR"));egl_destroy_image=reinterpret_cast<PFNEGLDESTROYIMAGEKHRPROC>(SDL_EGL_GetProcAddress("eglDestroyImageKHR"));egl_query_string=reinterpret_cast<PFNEGLQUERYSTRINGPROC>(SDL_EGL_GetProcAddress("eglQueryString"));image_target=reinterpret_cast<ImageTargetProc>(SDL_GL_GetProcAddress("glEGLImageTargetTexture2DOES"));if(egl_display!=EGL_NO_DISPLAY&&egl_create_image&&egl_destroy_image&&image_target){const char*ext=egl_query_string?egl_query_string(egl_display,EGL_EXTENSIONS):nullptr;const std::string extensions=ext?ext:"";drm_import_ready=extensions.find("EGL_EXT_image_dma_buf_import")!=std::string::npos;drm_modifiers=extensions.find("EGL_EXT_image_dma_buf_import_modifiers")!=std::string::npos;}
#endif
        return nv12_uniform>=0;}
    void ensure_texture_storage(int w,int h){if(w==texture_width&&h==texture_height)return;texture_width=w;texture_height=h;const int cw=(w+1)/2,ch=(h+1)/2;glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_2D,textures[0]);glTexImage2D(GL_TEXTURE_2D,0,GL_LUMINANCE,w,h,0,GL_LUMINANCE,GL_UNSIGNED_BYTE,nullptr);glActiveTexture(GL_TEXTURE1);glBindTexture(GL_TEXTURE_2D,textures[1]);glTexImage2D(GL_TEXTURE_2D,0,GL_LUMINANCE,cw,ch,0,GL_LUMINANCE,GL_UNSIGNED_BYTE,nullptr);glActiveTexture(GL_TEXTURE2);glBindTexture(GL_TEXTURE_2D,textures[2]);glTexImage2D(GL_TEXTURE_2D,0,GL_LUMINANCE,cw,ch,0,GL_LUMINANCE,GL_UNSIGNED_BYTE,nullptr);glActiveTexture(GL_TEXTURE3);glBindTexture(GL_TEXTURE_2D,textures[3]);glTexImage2D(GL_TEXTURE_2D,0,GL_LUMINANCE_ALPHA,cw,ch,0,GL_LUMINANCE_ALPHA,GL_UNSIGNED_BYTE,nullptr);}
    bool upload_plane_pbo(std::size_t plane,GLenum unit,GLuint texture,GLenum format,int width,int height,const std::uint8_t*src,int stride,int bpp){if(!pbo_ready||plane>=4||!src||width<=0||height<=0||stride==0||bpp<=0)return false;const std::size_t row_bytes=static_cast<std::size_t>(width)*static_cast<std::size_t>(bpp),bytes=row_bytes*static_cast<std::size_t>(height);if(bytes==0)return false;const GLuint pbo=unpack_buffers[pbo_phase*4+plane];glBindBuffer(GL_PIXEL_UNPACK_BUFFER,pbo);glBufferData(GL_PIXEL_UNPACK_BUFFER,static_cast<GLsizeiptr>(bytes),nullptr,GL_STREAM_DRAW);auto*mapped=static_cast<std::uint8_t*>(glMapBuffer(GL_PIXEL_UNPACK_BUFFER,GL_WRITE_ONLY));if(!mapped){glBindBuffer(GL_PIXEL_UNPACK_BUFFER,0);return false;}for(int y=0;y<height;++y)std::memcpy(mapped+static_cast<std::size_t>(y)*row_bytes,src+static_cast<std::ptrdiff_t>(y)*stride,row_bytes);if(glUnmapBuffer(GL_PIXEL_UNPACK_BUFFER)!=GL_TRUE){glBindBuffer(GL_PIXEL_UNPACK_BUFFER,0);return false;}glActiveTexture(unit);glBindTexture(GL_TEXTURE_2D,texture);glPixelStorei(GL_UNPACK_ROW_LENGTH,0);glTexSubImage2D(GL_TEXTURE_2D,0,0,0,width,height,format,GL_UNSIGNED_BYTE,nullptr);glBindBuffer(GL_PIXEL_UNPACK_BUFFER,0);return true;}
    void upload_plane(std::size_t plane,GLenum unit,GLuint texture,GLenum format,int width,int height,const std::uint8_t*src,int stride,int bpp,std::vector<std::uint8_t>&scratch){if(pbo_ready){if(upload_plane_pbo(plane,unit,texture,format,width,height,src,stride,bpp))return;}upload_plane_direct(unit,texture,format,width,height,src,stride,bpp,scratch);}
#if OPAL_HAVE_DRM_PRIME_EGL
    EGLImageKHR import_plane(const AVDRMFrameDescriptor&desc,const AVDRMPlaneDescriptor&plane,int width,int height,std::uint32_t fourcc){if(!drm_import_ready||plane.object_index<0||plane.object_index>=desc.nb_objects||width<=0||height<=0)return EGL_NO_IMAGE_KHR;const auto&object=desc.objects[plane.object_index];std::vector<EGLint>attrs={EGL_WIDTH,width,EGL_HEIGHT,height,EGL_LINUX_DRM_FOURCC_EXT,static_cast<EGLint>(fourcc),EGL_DMA_BUF_PLANE0_FD_EXT,object.fd,EGL_DMA_BUF_PLANE0_OFFSET_EXT,static_cast<EGLint>(plane.offset),EGL_DMA_BUF_PLANE0_PITCH_EXT,static_cast<EGLint>(plane.pitch)};
#ifdef EGL_DMA_BUF_PLANE0_MODIFIER_LO_EXT
        if(drm_modifiers&&object.format_modifier!=DRM_FORMAT_MOD_INVALID){attrs.push_back(EGL_DMA_BUF_PLANE0_MODIFIER_LO_EXT);attrs.push_back(static_cast<EGLint>(object.format_modifier&0xffffffffu));attrs.push_back(EGL_DMA_BUF_PLANE0_MODIFIER_HI_EXT);attrs.push_back(static_cast<EGLint>(object.format_modifier>>32));}
#endif
        attrs.push_back(EGL_NONE);return egl_create_image(egl_display,EGL_NO_CONTEXT,EGL_LINUX_DMA_BUF_EXT,nullptr,attrs.data());}
    bool bind_image(GLenum unit,GLuint texture,EGLImageKHR image){if(image==EGL_NO_IMAGE_KHR||!image_target)return false;glActiveTexture(unit);glBindTexture(GL_TEXTURE_2D,texture);image_target(GL_TEXTURE_2D,reinterpret_cast<void*>(image));return glGetError()==GL_NO_ERROR;}
    bool import_drm(const AVFrame*f,std::array<EGLImageKHR,3>&images,int&mode){if(!drm_import_ready||!f||f->format!=AV_PIX_FMT_DRM_PRIME||!f->data[0])return false;const auto*desc=reinterpret_cast<const AVDRMFrameDescriptor*>(f->data[0]);if(!desc||desc->nb_layers!=1)return false;const auto&layer=desc->layers[0];const int cw=(f->width+1)/2,ch=(f->height+1)/2;if(layer.format==DRM_FORMAT_NV12&&layer.nb_planes>=2){images[0]=import_plane(*desc,layer.planes[0],f->width,f->height,DRM_FORMAT_R8);images[1]=import_plane(*desc,layer.planes[1],cw,ch,DRM_FORMAT_GR88);if(images[0]==EGL_NO_IMAGE_KHR||images[1]==EGL_NO_IMAGE_KHR||!bind_image(GL_TEXTURE0,textures[0],images[0])||!bind_image(GL_TEXTURE3,textures[3],images[1]))return false;mode=2;return true;}if((layer.format==DRM_FORMAT_YUV420||layer.format==DRM_FORMAT_YVU420)&&layer.nb_planes>=3){const int u=layer.format==DRM_FORMAT_YVU420?2:1,v=layer.format==DRM_FORMAT_YVU420?1:2;images[0]=import_plane(*desc,layer.planes[0],f->width,f->height,DRM_FORMAT_R8);images[1]=import_plane(*desc,layer.planes[u],cw,ch,DRM_FORMAT_R8);images[2]=import_plane(*desc,layer.planes[v],cw,ch,DRM_FORMAT_R8);if(images[0]==EGL_NO_IMAGE_KHR||images[1]==EGL_NO_IMAGE_KHR||images[2]==EGL_NO_IMAGE_KHR||!bind_image(GL_TEXTURE0,textures[0],images[0])||!bind_image(GL_TEXTURE1,textures[1],images[1])||!bind_image(GL_TEXTURE2,textures[2],images[2]))return false;mode=0;return true;}return false;}
    void destroy_images(std::array<EGLImageKHR,3>&images){if(!egl_destroy_image||egl_display==EGL_NO_DISPLAY)return;for(auto&image:images)if(image!=EGL_NO_IMAGE_KHR){egl_destroy_image(egl_display,image);image=EGL_NO_IMAGE_KHR;}}
#endif
    void debug_timing(){if(!debug_enabled())return;const auto now=Clock::now();if(last_debug.time_since_epoch().count()!=0&&now-last_debug<std::chrono::seconds(1))return;last_debug=now;const auto upload=upload_latency.snapshot(),swap=swap_latency.snapshot();const char*path=renderer_active?(renderer_format==AV_PIX_FMT_NV12?"sdl-nv12":"sdl-yuv"):(drm_import_active?"dmabuf-egl":(pbo_ready?"pbo":"direct"));std::cerr<<"OPAL present upload_or_import_submit p50="<<upload.p50<<"ms p95="<<upload.p95<<"ms p99="<<upload.p99<<"ms swap_return p50="<<swap.p50<<"ms p95="<<swap.p95<<"ms p99="<<swap.p99<<"ms path="<<path<<" presentation="<<(immediate_swap?"immediate-active":"fallback")<<" photon_timing=unmeasured\n";}
};

VideoPresenter::VideoPresenter():impl_(std::make_unique<Impl>()){}
bool VideoPresenter::supports_cpu_upload_format(int format){return format==AV_PIX_FMT_YUV420P||format==AV_PIX_FMT_YUVJ420P||format==AV_PIX_FMT_NV12;}
bool VideoPresenter::drm_prime_supported_format(int format){return format==AV_PIX_FMT_DRM_PRIME;}
bool VideoPresenter::open(int sw,int sh,bool fullscreen,int source_format){close();if(sw<=0||sh<=0)return false;impl_=std::make_unique<Impl>();const std::string requested=env_value("OPAL_PRESENTER");const bool force_gl=requested=="opengl",force_sdl=requested=="sdl";const bool source_cpu=supports_cpu_upload_format(source_format),source_unknown=source_format<0;const bool try_sdl=!force_gl&&(force_sdl||source_cpu||source_unknown);SDL_WindowFlags base_flags=SDL_WINDOW_RESIZABLE|SDL_WINDOW_HIGH_PIXEL_DENSITY;if(fullscreen)base_flags|=SDL_WINDOW_FULLSCREEN;if(try_sdl){impl_->window=SDL_CreateWindow("OPAL",sw,sh,base_flags);if(impl_->window&&impl_->init_renderer()&&(source_unknown||impl_->ensure_renderer_texture(sw,sh,source_format))&&impl_->refresh_drawable_size(true))return true;if(impl_->render_texture){SDL_DestroyTexture(impl_->render_texture);impl_->render_texture=nullptr;}if(impl_->renderer){SDL_DestroyRenderer(impl_->renderer);impl_->renderer=nullptr;}if(impl_->window){SDL_DestroyWindow(impl_->window);impl_->window=nullptr;}impl_->renderer_active=false;if(force_sdl){close();return false;}}
    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER,1);SDL_GL_SetAttribute(SDL_GL_RED_SIZE,8);SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE,8);SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE,8);impl_->window=SDL_CreateWindow("OPAL",sw,sh,base_flags|SDL_WINDOW_OPENGL);if(!impl_->window){close();return false;}impl_->context=SDL_GL_CreateContext(impl_->window);if(!impl_->context){close();return false;}if(!SDL_GL_MakeCurrent(impl_->window,impl_->context)){close();return false;}impl_->immediate_swap=SDL_GL_SetSwapInterval(0);if(impl_->immediate_swap){int interval=1;if(!SDL_GL_GetSwapInterval(&interval)||interval!=0)impl_->immediate_swap=false;}if(!impl_->init_gl()){close();return false;}glDisable(GL_DEPTH_TEST);glDisable(GL_CULL_FACE);glDisable(GL_DITHER);glPixelStorei(GL_UNPACK_ALIGNMENT,1);glClearColor(0.f,0.f,0.f,1.f);if(!impl_->refresh_drawable_size(true)){close();return false;}return true;}
bool VideoPresenter::present_borrowed(DecodedVideoView decoded){const AVFrame*f=decoded.frame;if(!f||!impl_||!impl_->window||f->width<=0||f->height<=0)return false;if(impl_->renderer_active){if(f->format==AV_PIX_FMT_DRM_PRIME){AVFrame*transfer=av_frame_alloc();if(!transfer)return false;const bool transferred=av_hwframe_transfer_data(transfer,f,0)>=0&&av_frame_copy_props(transfer,f)>=0;if(!transferred){av_frame_free(&transfer);return false;}const bool ok=impl_->present_renderer(transfer);av_frame_free(&transfer);return ok;}return supports_cpu_upload_format(f->format)&&impl_->present_renderer(f);}if(!impl_->context)return false;const bool cpu=supports_cpu_upload_format(f->format),drm=f->format==AV_PIX_FMT_DRM_PRIME;if(!cpu&&!drm)return false;impl_->drm_import_active=false;if(!impl_->refresh_drawable_size())return false;const int ww=impl_->drawable_width,wh=impl_->drawable_height;glViewport(0,0,ww,wh);glClear(GL_COLOR_BUFFER_BIT);fitted_viewport(ww,wh,f->width,f->height);int nv12_mode=f->format==AV_PIX_FMT_NV12?1:0;const auto upload_begin=Clock::now();
#if OPAL_HAVE_DRM_PRIME_EGL
    std::array<EGLImageKHR,3>images{EGL_NO_IMAGE_KHR,EGL_NO_IMAGE_KHR,EGL_NO_IMAGE_KHR};
    if(drm){if(!impl_->import_drm(f,images,nv12_mode)){impl_->destroy_images(images);AVFrame*transfer=av_frame_alloc();if(!transfer)return false;const bool transferred=av_hwframe_transfer_data(transfer,f,0)>=0&&av_frame_copy_props(transfer,f)>=0;if(!transferred){av_frame_free(&transfer);return false;}const bool ok=present_borrowed({transfer,decoded.pts_us});av_frame_free(&transfer);return ok;}impl_->drm_import_active=true;}
#else
    if(drm){AVFrame*transfer=av_frame_alloc();if(!transfer)return false;const bool transferred=av_hwframe_transfer_data(transfer,f,0)>=0&&av_frame_copy_props(transfer,f)>=0;if(!transferred){av_frame_free(&transfer);return false;}const bool ok=present_borrowed({transfer,decoded.pts_us});av_frame_free(&transfer);return ok;}
#endif
    if(cpu){impl_->ensure_texture_storage(f->width,f->height);impl_->upload_plane(0,GL_TEXTURE0,impl_->textures[0],GL_LUMINANCE,f->width,f->height,f->data[0],f->linesize[0],1,impl_->scratch_y);if(f->format==AV_PIX_FMT_YUV420P||f->format==AV_PIX_FMT_YUVJ420P){const int cw=(f->width+1)/2,ch=(f->height+1)/2;impl_->upload_plane(1,GL_TEXTURE1,impl_->textures[1],GL_LUMINANCE,cw,ch,f->data[1],f->linesize[1],1,impl_->scratch_u);impl_->upload_plane(2,GL_TEXTURE2,impl_->textures[2],GL_LUMINANCE,cw,ch,f->data[2],f->linesize[2],1,impl_->scratch_v);}else{const int cw=(f->width+1)/2,ch=(f->height+1)/2;impl_->upload_plane(3,GL_TEXTURE3,impl_->textures[3],GL_LUMINANCE_ALPHA,cw,ch,f->data[1],f->linesize[1],2,impl_->scratch_uv);}if(impl_->pbo_ready)impl_->pbo_phase^=1;}
    const auto upload_end=Clock::now();impl_->upload_latency.push(elapsed_ms(upload_begin,upload_end));glUseProgram(impl_->program);glUniform1i(impl_->nv12_uniform,nv12_mode);glBegin(GL_TRIANGLE_STRIP);glTexCoord2f(0.f,1.f);glVertex2f(-1.f,-1.f);glTexCoord2f(1.f,1.f);glVertex2f(1.f,-1.f);glTexCoord2f(0.f,0.f);glVertex2f(-1.f,1.f);glTexCoord2f(1.f,0.f);glVertex2f(1.f,1.f);glEnd();glUseProgram(0);const auto swap_begin=Clock::now();if(!SDL_GL_SwapWindow(impl_->window)){
#if OPAL_HAVE_DRM_PRIME_EGL
        if(drm)impl_->destroy_images(images);
#endif
        impl_->drm_import_active=false;return false;}const auto swap_end=Clock::now();impl_->swap_latency.push(elapsed_ms(swap_begin,swap_end));
#if OPAL_HAVE_DRM_PRIME_EGL
    if(drm)impl_->destroy_images(images);
#endif
    ++impl_->presented;impl_->debug_timing();return true;}
bool VideoPresenter::present(DecodedVideoFrame decoded){AVFrame*f=decoded.frame;if(!f)return false;const bool ok=present_borrowed({f,decoded.pts_us});av_frame_free(&f);return ok;}
std::pair<int,int> VideoPresenter::drawable_size()const{if(!impl_||!impl_->window)return{0,0};if(impl_->drawable_width>0&&impl_->drawable_height>0)return{impl_->drawable_width,impl_->drawable_height};int w=0,h=0;if(!SDL_GetWindowSizeInPixels(impl_->window,&w,&h))return{0,0};return{w,h};}
std::pair<int,int> VideoPresenter::window_size()const{if(!impl_||!impl_->window)return{0,0};int w=0,h=0;if(!SDL_GetWindowSize(impl_->window,&w,&h))return{0,0};return{w,h};}
bool VideoPresenter::set_relative_mouse_mode(bool enabled){if(!impl_||!impl_->window)return false;if(!SDL_SetWindowRelativeMouseMode(impl_->window,enabled))return false;if(!SDL_SetWindowMouseGrab(impl_->window,enabled))return false;return enabled?SDL_HideCursor():SDL_ShowCursor();}
std::size_t VideoPresenter::pending_frame_count()const{return 0;}
std::uint64_t VideoPresenter::presented_frames()const{return impl_?impl_->presented:0;}
std::string VideoPresenter::backend_name()const{const char*driver=SDL_GetCurrentVideoDriver();const std::string base=driver&&*driver?driver:"unconfigured";if(impl_&&impl_->renderer_active)return base+"+sdl-renderer="+impl_->renderer_name;if(impl_&&impl_->drm_import_active)return base+"+opengl-dmabuf";return impl_&&impl_->pbo_ready?base+"+opengl-pbo":base+"+opengl";}
std::string VideoPresenter::presentation_mode()const{return impl_&&impl_->immediate_swap?"immediate-active":"fallback";}
bool VideoPresenter::is_open()const{return impl_&&impl_->window&&(impl_->renderer||impl_->context);}
void VideoPresenter::close(){if(!impl_)return;if(impl_->window){(void)SDL_SetWindowMouseGrab(impl_->window,false);(void)SDL_SetWindowRelativeMouseMode(impl_->window,false);(void)SDL_ShowCursor();}if(impl_->render_texture){SDL_DestroyTexture(impl_->render_texture);impl_->render_texture=nullptr;}if(impl_->renderer){SDL_DestroyRenderer(impl_->renderer);impl_->renderer=nullptr;}impl_->renderer_active=false;if(impl_->window&&impl_->context){SDL_GL_MakeCurrent(impl_->window,impl_->context);glBindBuffer(GL_PIXEL_UNPACK_BUFFER,0);if(impl_->unpack_buffers[0]){glDeleteBuffers(static_cast<GLsizei>(impl_->unpack_buffers.size()),impl_->unpack_buffers.data());impl_->unpack_buffers.fill(0);}if(impl_->program){glDeleteProgram(impl_->program);impl_->program=0;}if(impl_->textures[0]){glDeleteTextures(static_cast<GLsizei>(impl_->textures.size()),impl_->textures.data());impl_->textures.fill(0);}}if(impl_->context){SDL_GL_DestroyContext(impl_->context);impl_->context=nullptr;}if(impl_->window){SDL_DestroyWindow(impl_->window);impl_->window=nullptr;}}
VideoPresenter::~VideoPresenter(){close();}
}