#define GL_GLEXT_PROTOTYPES 1
#include <opal/video_present.hpp>

#include <GL/gl.h>
#include <GL/glx.h>
#include <X11/Xatom.h>
#include <algorithm>
#include <array>
#include <cstring>
#include <vector>

extern "C" {
#include <libavutil/pixfmt.h>
}

namespace opal {
namespace {

GLuint compile_shader(GLenum type,const char *source){GLuint shader=glCreateShader(type);if(!shader)return 0;glShaderSource(shader,1,&source,nullptr);glCompileShader(shader);GLint ok=GL_FALSE;glGetShaderiv(shader,GL_COMPILE_STATUS,&ok);if(!ok){glDeleteShader(shader);return 0;}return shader;}
GLuint make_program(){static const char *vertex=R"GLSL(#version 120
varying vec2 uv;void main(){gl_Position=gl_Vertex;uv=gl_MultiTexCoord0.xy;})GLSL";static const char *fragment=R"GLSL(#version 120
uniform sampler2D tex_y;uniform sampler2D tex_u;uniform sampler2D tex_v;uniform int nv12;varying vec2 uv;void main(){float y=texture2D(tex_y,uv).r;float u;float v;if(nv12!=0){vec4 c=texture2D(tex_uv,uv);u=c.r-0.5;v=c.a-0.5;}else{u=texture2D(tex_u,uv).r-0.5;v=texture2D(tex_v,uv).r-0.5;}y=max(0.0,1.1643*(y-0.0625));gl_FragColor=vec4(y+1.5958*v,y-0.39173*u-0.81290*v,y+2.017*u,1.0);})GLSL";GLuint vs=compile_shader(GL_VERTEX_SHADER,vertex),fs=compile_shader(GL_FRAGMENT_SHADER,fragment);if(!vs||!fs){if(vs)glDeleteShader(vs);if(fs)glDeleteShader(fs);return 0;}GLuint program=glCreateProgram();if(!program){glDeleteShader(vs);glDeleteShader(fs);return 0;}glAttachShader(program,vs);glAttachShader(program,fs);glLinkProgram(program);glDeleteShader(vs);glDeleteShader(fs);GLint ok=GL_FALSE;glGetProgramiv(program,GL_LINK_STATUS,&ok);if(!ok){glDeleteProgram(program);return 0;}return program;}
const void *upload_source(const std::uint8_t *src,int stride,int width,int height,int bpp,std::vector<std::uint8_t>&scratch,int&row_length){row_length=0;if(!src||width<=0||height<=0||bpp<=0)return nullptr;const int row_bytes=width*bpp;if(stride>0&&stride>=row_bytes&&stride%bpp==0){row_length=stride/bpp;return src;}scratch.resize(static_cast<std::size_t>(row_bytes)*height);for(int y=0;y<height;++y)std::memcpy(scratch.data()+static_cast<std::size_t>(y)*row_bytes,src+static_cast<std::ptrdiff_t>(y)*stride,row_bytes);return scratch.data();}
void upload_plane(GLenum unit,GLuint texture,GLenum format,int width,int height,const std::uint8_t*src,int stride,int bpp,std::vector<std::uint8_t>&scratch){int row_length=0;const void*pixels=upload_source(src,stride,width,height,bpp,scratch,row_length);if(!pixels)return;glActiveTexture(unit);glBindTexture(GL_TEXTURE_2D,texture);glPixelStorei(GL_UNPACK_ROW_LENGTH,row_length);glTexSubImage2D(GL_TEXTURE_2D,0,0,0,width,height,format,GL_UNSIGNED_BYTE,pixels);glPixelStorei(GL_UNPACK_ROW_LENGTH,0);}
void request_fullscreen(Display*d,Window w){Atom state=XInternAtom(d,"_NET_WM_STATE",False),fullscreen=XInternAtom(d,"_NET_WM_STATE_FULLSCREEN",False);if(state==None||fullscreen==None)return;XEvent e{};e.type=ClientMessage;e.xclient.window=w;e.xclient.message_type=state;e.xclient.format=32;e.xclient.data.l[0]=1;e.xclient.data.l[1]=static_cast<long>(fullscreen);XSendEvent(d,DefaultRootWindow(d),False,SubstructureRedirectMask|SubstructureNotifyMask,&e);}
void request_compositor_bypass(Display*d,Window w){Atom bypass=XInternAtom(d,"_NET_WM_BYPASS_COMPOSITOR",False);if(bypass==None)return;unsigned long enabled=1;XChangeProperty(d,w,bypass,XA_CARDINAL,32,PropModeReplace,reinterpret_cast<unsigned char*>(&enabled),1);}
void disable_swap_interval(Display*d,GLXDrawable drawable){using Ext=void(*)(Display*,GLXDrawable,int);using Mesa=int(*)(unsigned int);auto ext=reinterpret_cast<Ext>(glXGetProcAddressARB(reinterpret_cast<const GLubyte*>("glXSwapIntervalEXT")));if(ext){ext(d,drawable,0);return;}auto mesa=reinterpret_cast<Mesa>(glXGetProcAddressARB(reinterpret_cast<const GLubyte*>("glXSwapIntervalMESA")));if(mesa)mesa(0);}
void fitted_viewport(int ww,int wh,int sw,int sh){ww=std::max(1,ww);wh=std::max(1,wh);sw=std::max(1,sw);sh=std::max(1,sh);const long long lhs=static_cast<long long>(ww)*sh,rhs=static_cast<long long>(wh)*sw;int w=ww,h=wh,x=0,y=0;if(lhs>rhs){w=std::max(1,static_cast<int>(static_cast<long long>(wh)*sw/sh));x=(ww-w)/2;}else if(lhs<rhs){h=std::max(1,static_cast<int>(static_cast<long long>(ww)*sh/sw));y=(wh-h)/2;}glViewport(x,y,w,h);}
}

struct VideoPresenter::Impl{Display*display=nullptr;Window window=0;Colormap colormap=0;GLXContext context=nullptr;GLuint program=0;GLint nv12_uniform=-1;std::array<GLuint,4>textures{};int source_width=0,source_height=0,texture_width=0,texture_height=0,window_width=1,window_height=1;std::uint64_t presented_frames=0;std::vector<std::uint8_t>scratch_y,scratch_u,scratch_v,scratch_uv;bool init_gl(){program=make_program();if(!program)return false;glGenTextures(static_cast<GLsizei>(textures.size()),textures.data());for(GLuint t:textures){glBindTexture(GL_TEXTURE_2D,t);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_CLAMP_TO_EDGE);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE);}glUseProgram(program);glUniform1i(glGetUniformLocation(program,"tex_y"),0);glUniform1i(glGetUniformLocation(program,"tex_u"),1);glUniform1i(glGetUniformLocation(program,"tex_v"),2);glUniform1i(glGetUniformLocation(program,"tex_uv"),3);nv12_uniform=glGetUniformLocation(program,"nv12");glUseProgram(0);return nv12_uniform>=0;}void ensure_texture_storage(int w,int h){if(w==texture_width&&h==texture_height)return;texture_width=w;texture_height=h;const int cw=(w+1)/2,ch=(h+1)/2;glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_2D,textures[0]);glTexImage2D(GL_TEXTURE_2D,0,GL_LUMINANCE,w,h,0,GL_LUMINANCE,GL_UNSIGNED_BYTE,nullptr);glActiveTexture(GL_TEXTURE1);glBindTexture(GL_TEXTURE_2D,textures[1]);glTexImage2D(GL_TEXTURE_2D,0,GL_LUMINANCE,cw,ch,0,GL_LUMINANCE,GL_UNSIGNED_BYTE,nullptr);glActiveTexture(GL_TEXTURE2);glBindTexture(GL_TEXTURE_2D,textures[2]);glTexImage2D(GL_TEXTURE_2D,0,GL_LUMINANCE,cw,ch,0,GL_LUMINANCE,GL_UNSIGNED_BYTE,nullptr);glActiveTexture(GL_TEXTURE3);glBindTexture(GL_TEXTURE_2D,textures[3]);glTexImage2D(GL_TEXTURE_2D,0,GL_LUMINANCE_ALPHA,cw,ch,0,GL_LUMINANCE_ALPHA,GL_UNSIGNED_BYTE,nullptr);}void consume_window_events(){if(!display)return;while(XPending(display)>0){XEvent e{};XNextEvent(display,&e);if(e.type==ConfigureNotify&&e.xconfigure.window==window){window_width=std::max(1,e.xconfigure.width);window_height=std::max(1,e.xconfigure.height);}}}};

VideoPresenter::VideoPresenter():impl_(std::make_unique<Impl>()){}
bool VideoPresenter::open(int sw,int sh,bool fullscreen){close();if(sw<=0||sh<=0)return false;impl_=std::make_unique<Impl>();impl_->display=XOpenDisplay(nullptr);if(!impl_->display)return false;int screen=DefaultScreen(impl_->display);int attrs[]={GLX_RGBA,GLX_DOUBLEBUFFER,GLX_RED_SIZE,8,GLX_GREEN_SIZE,8,GLX_BLUE_SIZE,8,None};XVisualInfo*visual=glXChooseVisual(impl_->display,screen,attrs);if(!visual){close();return false;}impl_->colormap=XCreateColormap(impl_->display,RootWindow(impl_->display,screen),visual->visual,AllocNone);XSetWindowAttributes swa{};swa.colormap=impl_->colormap;swa.event_mask=StructureNotifyMask|ExposureMask|KeyPressMask|KeyReleaseMask|PointerMotionMask|ButtonPressMask|ButtonReleaseMask;unsigned w=fullscreen?static_cast<unsigned>(DisplayWidth(impl_->display,screen)):static_cast<unsigned>(sw),h=fullscreen?static_cast<unsigned>(DisplayHeight(impl_->display,screen)):static_cast<unsigned>(sh);impl_->window_width=static_cast<int>(w);impl_->window_height=static_cast<int>(h);impl_->window=XCreateWindow(impl_->display,RootWindow(impl_->display,screen),0,0,w,h,0,visual->depth,InputOutput,visual->visual,CWColormap|CWEventMask,&swa);if(impl_->window)impl_->context=glXCreateContext(impl_->display,visual,nullptr,True);XFree(visual);if(!impl_->window||!impl_->context){close();return false;}XStoreName(impl_->display,impl_->window,"OPAL");request_compositor_bypass(impl_->display,impl_->window);XMapRaised(impl_->display,impl_->window);XFlush(impl_->display);if(fullscreen)request_fullscreen(impl_->display,impl_->window);if(!glXMakeCurrent(impl_->display,impl_->window,impl_->context)){close();return false;}disable_swap_interval(impl_->display,impl_->window);impl_->source_width=sw;impl_->source_height=sh;if(!impl_->init_gl()){close();return false;}glDisable(GL_DEPTH_TEST);glDisable(GL_CULL_FACE);glPixelStorei(GL_UNPACK_ALIGNMENT,1);glClearColor(0.f,0.f,0.f,1.f);return true;}
bool VideoPresenter::present_borrowed(DecodedVideoView decoded){const AVFrame*f=decoded.frame;if(!f||!impl_||!impl_->display||!impl_->window||!impl_->context||f->width<=0||f->height<=0)return false;const bool yuv420=f->format==AV_PIX_FMT_YUV420P||f->format==AV_PIX_FMT_YUVJ420P,nv12=f->format==AV_PIX_FMT_NV12;if(!yuv420&&!nv12)return false;if(!glXMakeCurrent(impl_->display,impl_->window,impl_->context))return false;impl_->consume_window_events();glViewport(0,0,impl_->window_width,impl_->window_height);glClear(GL_COLOR_BUFFER_BIT);fitted_viewport(impl_->window_width,impl_->window_height,f->width,f->height);impl_->ensure_texture_storage(f->width,f->height);upload_plane(GL_TEXTURE0,impl_->textures[0],GL_LUMINANCE,f->width,f->height,f->data[0],f->linesize[0],1,impl_->scratch_y);if(yuv420){const int cw=(f->width+1)/2,ch=(f->height+1)/2;upload_plane(GL_TEXTURE1,impl_->textures[1],GL_LUMINANCE,cw,ch,f->data[1],f->linesize[1],1,impl_->scratch_u);upload_plane(GL_TEXTURE2,impl_->textures[2],GL_LUMINANCE,cw,ch,f->data[2],f->linesize[2],1,impl_->scratch_v);}else{const int cw=(f->width+1)/2,ch=(f->height+1)/2;upload_plane(GL_TEXTURE3,impl_->textures[3],GL_LUMINANCE_ALPHA,cw,ch,f->data[1],f->linesize[1],2,impl_->scratch_uv);}glUseProgram(impl_->program);glUniform1i(impl_->nv12_uniform,nv12?1:0);glBegin(GL_TRIANGLE_STRIP);glTexCoord2f(0.f,1.f);glVertex2f(-1.f,-1.f);glTexCoord2f(1.f,1.f);glVertex2f(1.f,-1.f);glTexCoord2f(0.f,0.f);glVertex2f(-1.f,1.f);glTexCoord2f(1.f,0.f);glVertex2f(1.f,1.f);glEnd();glUseProgram(0);glXSwapBuffers(impl_->display,impl_->window);glFlush();++impl_->presented_frames;return true;}
bool VideoPresenter::present(DecodedVideoFrame decoded){AVFrame*f=decoded.frame;if(!f)return false;const bool ok=present_borrowed({f,decoded.pts_us});av_frame_free(&f);return ok;}
Window VideoPresenter::x11_window()const{return impl_?impl_->window:0;}
std::pair<int,int> VideoPresenter::drawable_size()const{if(!impl_||!impl_->display||!impl_->window)return{0,0};XWindowAttributes wa{};if(!XGetWindowAttributes(impl_->display,impl_->window,&wa))return{0,0};return{wa.width,wa.height};}
std::size_t VideoPresenter::pending_frame_count()const{return 0;}
std::uint64_t VideoPresenter::presented_frames()const{return impl_?impl_->presented_frames:0;}
void VideoPresenter::close(){if(!impl_)return;if(impl_->display&&impl_->context&&impl_->window)glXMakeCurrent(impl_->display,impl_->window,impl_->context);if(impl_->program){glDeleteProgram(impl_->program);impl_->program=0;}if(impl_->textures[0]){glDeleteTextures(static_cast<GLsizei>(impl_->textures.size()),impl_->textures.data());impl_->textures.fill(0);}if(impl_->display&&impl_->context){glXMakeCurrent(impl_->display,None,nullptr);glXDestroyContext(impl_->display,impl_->context);impl_->context=nullptr;}if(impl_->display&&impl_->window){XDestroyWindow(impl_->display,impl_->window);impl_->window=0;}if(impl_->display&&impl_->colormap){XFreeColormap(impl_->display,impl_->colormap);impl_->colormap=0;}if(impl_->display){XCloseDisplay(impl_->display);impl_->display=nullptr;}}
VideoPresenter::~VideoPresenter(){close();}
}
