#include <opal/video_sender.hpp>

#include <opal/config.hpp>
#include <opal/media_profile.hpp>
#include <opal/udp_transport.hpp>
#include <opal/video_capture.hpp>
#include <opal/video_feedback.hpp>
#include <opal/video_packet.hpp>
#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <mutex>
#include <span>
#include <sstream>
#include <thread>
#include <utility>
#include <vector>

namespace opal { namespace {
using Clock=std::chrono::steady_clock;
constexpr std::uint64_t kFirstMediaSequence=1ULL<<32;
constexpr std::uint64_t kFrameSequenceMask=(1ULL<<62)-1;
constexpr std::uint64_t kAudioFrameDomain=2ULL<<62;
constexpr std::uint64_t kAuxFrameDomain=1ULL<<62;
std::uint64_t monotonic_us(){return static_cast<std::uint64_t>(std::chrono::duration_cast<std::chrono::microseconds>(Clock::now().time_since_epoch()).count());}
bool debug_enabled(){const char *v=std::getenv("OPAL_DEBUG");return v&&*v&&std::string(v)!="0";}
void put32(std::vector<std::uint8_t> &out,std::uint32_t value){out.push_back(static_cast<std::uint8_t>(value>>24));out.push_back(static_cast<std::uint8_t>(value>>16));out.push_back(static_cast<std::uint8_t>(value>>8));out.push_back(static_cast<std::uint8_t>(value));}
}

struct VideoSender::Impl {
    std::unique_ptr<DirectVideoPath> owned_path;VideoKeys keys;std::uint64_t session_id=0;std::uint32_t generation=0;MediaDatagramSend datagram_send;
    StreamOptions stream;bool audio=false;std::function<void(const std::string&)> control_send;VideoCapture capture;std::unique_ptr<VideoCipher> cipher;std::array<std::uint8_t,kVideoMaxDatagramBytes> wire_buffer{};std::thread thread,keepalive_thread;
    std::atomic<bool> run{false},idr_requested{false},video_chain_valid{false},remote_debug{false};std::atomic<int> target_kbps{30000},active_kbps{30000};std::atomic<std::uint64_t> stale{0},idr_requests{0},capture_restarts{0},debug_frame_id{0},debug_frame_bytes{0};std::atomic<std::uint32_t> debug_data_fragments{0},debug_fec_fragments{0},debug_send_span_us{0},debug_capture_to_packet_us{0};
    std::unique_ptr<BitrateController> controller;std::mutex feedback_mu,send_mu;std::uint64_t packet_sequence=kFirstMediaSequence,video_frame_id=1,audio_frame_id=1,aux_frame_id=1;Clock::time_point last_restart{},token_time{},last_debug{};double tokens=0.0,capture_to_packet_ewma=0.0;std::string portal_token;int test_drop_fragments=0;bool test_drop_done=false;

    bool initialize(VideoKeys video_keys,std::uint64_t sid,std::uint32_t gen,const StreamOptions&s,bool with_audio,MediaDatagramSend send,std::function<void(const std::string&)>control){if(sid==0||gen==0||!send)return false;keys=video_keys;session_id=sid;generation=gen;stream=s;audio=with_audio;datagram_send=std::move(send);control_send=std::move(control);cipher=std::make_unique<VideoCipher>(keys);if(!cipher->valid())return false;const int ceiling=automatic_bitrate_kbps(stream.max_width,stream.max_height,stream.fps);controller=std::make_unique<BitrateController>(ceiling);target_kbps.store(ceiling);active_kbps.store(ceiling);portal_token=(Paths::load().root/"portal-session.token").string();if(const char *drop=std::getenv("OPAL_TEST_DROP_FRAGMENTS");drop&&*drop)try{test_drop_fragments=std::clamp(std::stoi(drop),0,10);}catch(...){test_drop_fragments=0;}return start_capture();}
    std::uint64_t next_frame_id(VideoMediaType type){std::uint64_t value=0,domain=0;if(type==VideoMediaType::VideoH264)value=video_frame_id++;else if(type==VideoMediaType::AudioAac){value=audio_frame_id++;domain=kAudioFrameDomain;}else{value=aux_frame_id++;domain=kAuxFrameDomain;}return value&&value<=kFrameSequenceMask?domain|value:0;}
    void invalidate_video_chain(){video_chain_valid.store(false,std::memory_order_release);if(!idr_requested.exchange(true,std::memory_order_acq_rel))idr_requests.fetch_add(1,std::memory_order_relaxed);}
    bool start_capture(){const int bitrate=std::max(1000,target_kbps.load());if(!capture.start(stream,bitrate,audio,portal_token))return false;active_kbps.store(bitrate);video_chain_valid.store(false,std::memory_order_release);last_restart=Clock::now();{std::lock_guard<std::mutex>lock(send_mu);tokens=static_cast<double>(sender_burst_budget_bytes(bitrate,stream.fps,false));token_time=last_restart;}return true;}
    bool restart_capture(){idr_requested.store(false,std::memory_order_release);capture.stop();if(!start_capture())return false;capture_restarts.fetch_add(1,std::memory_order_relaxed);send_configs();return true;}
    void refill_tokens(double capacity,int pacing_kbps){const auto now=Clock::now();if(token_time.time_since_epoch().count()==0)token_time=now;const double us=static_cast<double>(std::chrono::duration_cast<std::chrono::microseconds>(now-token_time).count());token_time=now;const double bytes_per_us=std::max(0.001,static_cast<double>(pacing_kbps)/8000.0);tokens=std::min(capacity,tokens+us*bytes_per_us);}
    bool paced_send(std::span<const std::uint8_t>wire,Clock::time_point deadline,double capacity,int pacing_kbps){if(wire.empty()||wire.size()>kVideoMaxDatagramBytes||capacity<static_cast<double>(wire.size())||!datagram_send)return false;for(;;){const auto now=Clock::now();if(now>=deadline)return false;refill_tokens(capacity,pacing_kbps);if(tokens>=wire.size())break;const double bytes_per_us=std::max(0.001,static_cast<double>(pacing_kbps)/8000.0);const auto wait_us=static_cast<long long>(std::ceil((wire.size()-tokens)/bytes_per_us));if(now+std::chrono::microseconds(wait_us)>deadline)return false;std::this_thread::sleep_for(std::chrono::microseconds(std::clamp<long long>(wait_us,50,1000)));if(!run.load())return false;}if(Clock::now()>=deadline)return false;tokens-=wire.size();return datagram_send(wire);}
    bool encrypt_packet(const VideoPacketHeader &header,std::span<const std::uint8_t>payload,std::size_t&wire_size){wire_size=0;if(!cipher||!cipher->valid())return false;const auto aad=serialize_video_header(header);std::copy(aad.begin(),aad.end(),wire_buffer.begin());std::size_t sealed_size=0;auto sealed_output=std::span<std::uint8_t>(wire_buffer).subspan(aad.size());if(!cipher->seal(header.packet_sequence,aad,payload,sealed_output,sealed_size))return false;wire_size=aad.size()+sealed_size;return wire_size<=wire_buffer.size();}
    void record_video_send(std::uint64_t frame_id,std::size_t bytes,std::uint32_t data_fragments,std::uint32_t fec_fragments,std::uint64_t first_send_us,std::uint64_t last_send_us){debug_frame_id.store(frame_id);debug_frame_bytes.store(bytes);debug_data_fragments.store(data_fragments);debug_fec_fragments.store(fec_fragments);const auto span=last_send_us>=first_send_us?last_send_us-first_send_us:0;debug_send_span_us.store(static_cast<std::uint32_t>(std::min<std::uint64_t>(span,0xffffffffULL)));}
    bool send_frame(VideoMediaType type,std::uint16_t flags,std::span<const std::uint8_t>data,std::uint64_t capture_time=0){std::lock_guard<std::mutex>send_lock(send_mu);const bool video=type==VideoMediaType::VideoH264&&(flags&FrameConfig)==0;const bool keyframe=video&&(flags&FrameKeyframe)!=0;if(video&&!keyframe&&!video_chain_valid.load(std::memory_order_acquire))return false;const auto assigned_frame_id=next_frame_id(type);if(!assigned_frame_id)return false;const auto start=Clock::now();const bool ordinary=video&&!keyframe;const bool audio_frame=type==VideoMediaType::AudioAac&&(flags&FrameConfig)==0;const auto deadline=start+(ordinary?std::chrono::microseconds(1000000/std::max(15,stream.fps)):(audio_frame?std::chrono::milliseconds(10):std::chrono::milliseconds(250)));const double burst_capacity=static_cast<double>(sender_burst_budget_bytes(target_kbps.load(),stream.fps,keyframe));const int pacing_kbps=sender_pacing_rate_kbps(target_kbps.load(),keyframe);if(keyframe){tokens=std::max(tokens,burst_capacity);token_time=start;}VideoFragmentCursor cursor(type,flags,generation,session_id,assigned_frame_id,capture_time?capture_time:monotonic_us(),data,packet_sequence,use_fec_for_media(type));if(!cursor.valid())return false;int failures=0,deliberately_dropped=0;bool any=false;std::uint32_t data_fragments=0,fec_fragments=0;std::uint64_t first_send_us=0,last_send_us=0;const bool inject_drop=!test_drop_done&&type==VideoMediaType::VideoH264&&(flags&FrameConfig)==0&&test_drop_fragments>0;VideoPacketHeader header;std::span<const std::uint8_t>payload;while(cursor.next(header,payload)){any=true;if(header.media_type==VideoMediaType::Fec)++fec_fragments;else ++data_fragments;if(inject_drop&&header.media_type!=VideoMediaType::Fec&&header.fragment_count>=static_cast<std::uint16_t>(test_drop_fragments)&&deliberately_dropped<test_drop_fragments){++deliberately_dropped;continue;}std::size_t wire_size=0;if(!encrypt_packet(header,payload,wire_size)||!paced_send(std::span<const std::uint8_t>(wire_buffer.data(),wire_size),deadline,burst_capacity,pacing_kbps)){++failures;if(ordinary||audio_frame)break;}else{const auto sent=monotonic_us();if(!first_send_us)first_send_us=sent;last_send_us=sent;}}if(inject_drop&&deliberately_dropped==test_drop_fragments)test_drop_done=true;if(video)record_video_send(assigned_frame_id,data.size(),data_fragments,fec_fragments,first_send_us,last_send_us);if(!any)return false;if(failures){if(video)invalidate_video_chain();if(ordinary||audio_frame)stale.fetch_add(1);else if(type!=VideoMediaType::Keepalive)idr_requested.store(true);return false;}if(keyframe){video_chain_valid.store(true,std::memory_order_release);idr_requested.store(false,std::memory_order_release);}return true;}
    bool send_keepalive(){return send_frame(VideoMediaType::Keepalive,0,{},monotonic_us());}
    HostMediaDebugSample debug_snapshot()const{HostMediaDebugSample sample;sample.frame_id=debug_frame_id.load();sample.frame_bytes=debug_frame_bytes.load();sample.data_fragments=debug_data_fragments.load();sample.fec_fragments=debug_fec_fragments.load();sample.send_span_us=debug_send_span_us.load();sample.capture_to_packet_us=debug_capture_to_packet_us.load();sample.target_kbps=target_kbps.load();sample.active_kbps=active_kbps.load();sample.stale_frames=stale.load();sample.idr_requests=idr_requests.load();sample.restarts=capture_restarts.load();sample.chain_valid=video_chain_valid.load(std::memory_order_acquire);return sample;}
    void keepalive_loop(){Clock::time_point last_remote_debug{};while(run.load()){std::this_thread::sleep_for(std::chrono::milliseconds(250));if(!run.load())break;send_keepalive();const auto now=Clock::now();if(remote_debug.load(std::memory_order_acquire)&&(last_remote_debug.time_since_epoch().count()==0||now-last_remote_debug>=std::chrono::seconds(1))){last_remote_debug=now;if(control_send)control_send(host_media_debug_line(generation,debug_snapshot()));}}}
    void send_configs(){for(const auto &config:capture.configs()){if(config.kind==MediaKind::VideoH264){if(!config.extradata.empty())send_frame(VideoMediaType::VideoH264,FrameConfig,config.extradata);continue;}if(config.sample_rate<=0||config.channels<=0||config.channels>255)continue;std::vector<std::uint8_t>payload;payload.reserve(5+config.extradata.size());put32(payload,static_cast<std::uint32_t>(config.sample_rate));payload.push_back(static_cast<std::uint8_t>(config.channels));payload.insert(payload.end(),config.extradata.begin(),config.extradata.end());send_frame(VideoMediaType::AudioAac,FrameConfig,payload);}}
    bool maybe_restart(){const auto now=Clock::now();const int target=target_kbps.load(),active=std::max(1,active_kbps.load());const bool material_change=std::abs(target-active)*100>=active*15;const bool bitrate_down=material_change&&target<active&&now-last_restart>=std::chrono::milliseconds(250);const bool bitrate_up=material_change&&target>active&&now-last_restart>=std::chrono::seconds(2);const bool idr_change=idr_requested.load()&&now-last_restart>=std::chrono::milliseconds(250);if(!bitrate_down&&!bitrate_up&&!idr_change)return true;return restart_capture();}
    void debug_sample(std::uint64_t capture_time_us){if(!capture_time_us)return;const auto now_us=monotonic_us();const double sample=now_us>capture_time_us?static_cast<double>(now_us-capture_time_us)/1000.0:0.0;capture_to_packet_ewma=capture_to_packet_ewma==0.0?sample:capture_to_packet_ewma*0.8+sample*0.2;debug_capture_to_packet_us.store(static_cast<std::uint32_t>(std::min(4294967295.0,capture_to_packet_ewma*1000.0)));const auto now=Clock::now();if(debug_enabled()&&(last_debug.time_since_epoch().count()==0||now-last_debug>=std::chrono::seconds(1))){last_debug=now;std::cerr<<format_host_media_debug(debug_snapshot())<<"\n";}}
    void loop(){send_configs();EncodedMediaView unit;while(run.load()){if(!maybe_restart()){run.store(false);break;}if(!capture.next_view(unit,100)){if(capture.ended()&&!restart_capture()){run.store(false);break;}continue;}const auto now_us=monotonic_us();const auto age_us=unit.capture_time_us&&now_us>unit.capture_time_us?now_us-unit.capture_time_us:0;if(unit.kind==MediaKind::VideoH264&&age_us>capture_stale_budget_us(stream.fps)){stale.fetch_add(1);invalidate_video_chain();debug_sample(unit.capture_time_us);continue;}if(unit.kind==MediaKind::AudioAac&&age_us>40000)continue;const auto type=unit.kind==MediaKind::VideoH264?VideoMediaType::VideoH264:VideoMediaType::AudioAac;if(type==VideoMediaType::VideoH264&&!unit.keyframe&&!video_chain_valid.load(std::memory_order_acquire)){debug_sample(unit.capture_time_us);continue;}const std::uint16_t flags=unit.keyframe?FrameKeyframe:0;if(!send_frame(type,flags,unit.data,unit.capture_time_us)&&type==VideoMediaType::VideoH264)invalidate_video_chain();debug_sample(unit.capture_time_us);}capture.stop();}
    bool handle_control(const std::string&line){bool enabled=false;if(parse_debug_media_request_line(line,generation,enabled)){remote_debug.store(enabled,std::memory_order_release);return true;}{std::istringstream in(line);std::string word,extra;unsigned long long gen=0;if((in>>word>>gen)&&word=="REQUEST_IDR"&&gen==generation&&!(in>>extra)){invalidate_video_chain();return true;}}VideoFeedbackSample sample;if(parse_video_feedback_line(line,generation,sample)){std::lock_guard<std::mutex>lock(feedback_mu);if(controller)target_kbps.store(controller->on_feedback(sample,Clock::now()));return true;}std::int64_t t0=0,t1=0,t2=0;if(parse_clock_sync_line(line,generation,t0,t1,t2)&&t1==0&&t2==0){const auto receive=static_cast<std::int64_t>(monotonic_us());const auto send=static_cast<std::int64_t>(monotonic_us());if(control_send)control_send(clock_sync_reply_line(generation,t0,receive,send));return true;}return false;}
};

VideoSender::VideoSender():impl_(std::make_unique<Impl>()){}
bool VideoSender::start(DirectVideoPath path,const StreamOptions&stream,bool audio,std::function<void(const std::string&)>control_send){stop();impl_=std::make_unique<Impl>();if(path.socket.fd<0||path.peer_len==0||path.session_id==0||path.generation==0)return false;impl_->owned_path=std::make_unique<DirectVideoPath>(std::move(path));auto*owned=impl_->owned_path.get();MediaDatagramSend send=[owned](std::span<const std::uint8_t>wire){return send_datagram(owned->socket.fd,owned->peer,owned->peer_len,wire);};if(!impl_->initialize(owned->keys,owned->session_id,owned->generation,stream,audio,std::move(send),std::move(control_send)))return false;impl_->run.store(true);impl_->thread=std::thread([this]{impl_->loop();});impl_->keepalive_thread=std::thread([this]{impl_->keepalive_loop();});return true;}
bool VideoSender::start_native(const VideoKeys&keys,std::uint64_t session_id,std::uint32_t generation,const StreamOptions&stream,bool audio,MediaDatagramSend send,std::function<void(const std::string&)>control_send){stop();impl_=std::make_unique<Impl>();if(!impl_->initialize(keys,session_id,generation,stream,audio,std::move(send),std::move(control_send)))return false;impl_->run.store(true);impl_->thread=std::thread([this]{impl_->loop();});impl_->keepalive_thread=std::thread([this]{impl_->keepalive_loop();});return true;}
void VideoSender::request_idr(){if(impl_)impl_->invalidate_video_chain();}bool VideoSender::handle_control_line(const std::string&line){return impl_&&impl_->handle_control(line);}void VideoSender::set_target_bitrate(int kbps){if(impl_)impl_->target_kbps.store(std::max(1000,kbps));}int VideoSender::target_bitrate()const{return impl_?impl_->target_kbps.load():0;}std::size_t VideoSender::queued_frames()const{return 0;}std::size_t VideoSender::queued_bytes()const{return 0;}std::uint64_t VideoSender::stale_frames()const{return impl_?impl_->stale.load():0;}
void VideoSender::stop(){if(!impl_)return;impl_->run.store(false);if(impl_->thread.joinable())impl_->thread.join();if(impl_->keepalive_thread.joinable())impl_->keepalive_thread.join();}VideoSender::~VideoSender(){stop();}

}
