#define GL_GLEXT_PROTOTYPES 1
#include <opal/video_present.hpp>
#include <opal/latency_window.hpp>

#include <SDL3/SDL.h>
#include <GL/gl.h>
#include <algorithm>
#include <array>
#include <chrono>
#include <cstddef>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <string>
#include <vector>

extern "C" {
#include <libavutil/pixfmt.h>
}

namespace opal {
namespace {
using Clock=std::chrono::steady_clock;
bool debug_enabled(){const char*v=std::getenv("OPAL_DEBUG");return v&&*v&&std::string(v)!="0";}
double elapsed_ms(Clock::time_point begin,Clock::time_point end){return std::chrono::duration<double,std::milli>(end-begin).count();}
GLuint compile_shader(GLenum type,const char*source){GLuint shader=glCreateShader(type);if(!shader)return 0;glShaderSource(shader,1,&source,nullptr);glCompileShader(shader);GLint ok=GL_FALSE;glGetShaderiv(shader,GL_COMPILE_STATUS,&ok);if(!ok){glDeleteShader(shader);return 0;}return shader;}
GLuint make_program(){static const char*vertex=R"GLSL(#version 120
varying vec2 uv;void main(){gl_Position=gl_Vertex;uv=gl_MultiTexCoord0.xy;})GLSL";static const char*fragment=R"GLSL(#version 120
uniform sampler2D tex_y;uniform sampler2D tex_u;uniform sampler2D tex_v;uniform sampler2D tex_uv;uniform int nv12;varying vec2 uv;void main(){float y=texture2D(tex_y,uv).r;float u;float v;if(nv12!=0){vec4 c=texture2D(tex_uv,uv);u=c.r-0.5;v=c.a-0.5;}else{u=texture2D(tex_u,uv).r-0.5;v=texture2D(tex_v,uv).r-0.5;}y=max(0.0,1.1643*(y-0.0625));gl_FragColor=vec4(y+1.5958*v,y-0.39173*u-0.81290*v,y+2.017*u,1.0);})GLSL";GLuint vs=compile_shader(GL_VERTEX_SHADER,vertex),fs=compile_shader(GL_FRAGMENT_SHADER,fragment);if(!vs||!fs){if(vs)glDeleteShader(vs);if(fs)glDeleteShader(fs);return 0;}GLuint program=glCreateProgram();if(!program){glDeleteShader(vs);glDeleteShader(fs);return 0;}glAttachShader(program,vs);glAttachShader(program,fs);glLinkProgram(program);glDeleteShader(vs);glDeleteShader(fs);GLint ok=GL_FALSE;glGetProgramiv(program,GL_LINK_STATUS,&ok);if(!ok){glDeleteProgram(program);return 0;}return program;}
const void*upload_source(const std::uint8_t*src,int stride,int width,int height,int bpp,std::vector<std::uint8_t>&scratch,int&row_length){row_length=0;if(!src||width<=0||height<=0||bpp<=0)return nullptr;const int row_bytes=width*bpp;if(stride>0&&stride>=row_bytes&&stride%bpp==0){row_length=stride/bpp;return src;}scratch.resize(static_cast<std::size_t>(row_bytes)*height);for(int y=0;y<height;++y)std::memcpy(scratch.data()+static_cast<std::size_t>(y)*row_bytes,src+static_cast<std::ptrdiff_t>(y)*stride,row_bytes);return scratch.data();}
void upload_plane_direct(GLenum unit,GLuint texture,GLenum format,int width,int height,const std::uint8_t*src,int stride,int bpp,std::vector<std::uint8_t>&scratch){int row_length=0;const void*pixels=upload_source(src,stride,width,height,bpp,scratch,row_length);if(!pixels)return;glBindBuffer(GL_PIXEL_UNPACK_BUFFER,0);glActiveTexture(unit);glBindTexture(GL_TEXTURE_2D,texture);glPixelStorei(GL_UNPACK_ROW_LENGTH,row_length);glTexSubImage2D(GL_TEXTURE_2D,0,0,0,width,height,format,GL_UNSIGNED_BYTE,pixels);glPixelStorei(GL_UNPACK_ROW_LENGTH,0);}
void fitted_viewport(int ww,int wh,int sw,int sh){ww=std::max(1,ww);wh=std::max(1,wh);sw=std::max(1,sw);sh=std::max(1,sh);const long long lhs=static_cast<long long>(ww)*sh,rhs=static_cast<long long>(wh)*sw;int w=ww,h=wh,x=0,y=0;if(lhs>rhs){w=std::max(1,static_cast<int>(static_cast<long long>(wh)*sw/sh));x=(ww-w)/2;}else if(lhs<rhs){h=std::max(1,static_cast<int>(static_cast<long long>(ww)*sh/sw));y=(wh-h)/2;}glViewport(x,y,w,h);}
}

struct VideoPresenter::Impl{
    SDL_Window*window=nullptr;SDL_GLContext context=nullptr;GLuint program=0;GLint nv12_uniform=-1;std::array<GLuint,4>textures{};std::array<GLuint,8>unpack_buffers{};int texture_width=0,texture_height=0,drawable_width=0,drawable_height=0;std::uint64_t presented=0,last_size_refresh=0;std::size_t pbo_phase=0;bool pbo_ready=false,immediate_swap=false;std::vector<std::uint8_t>scratch_y,scratch_u,scratch_v,scratch_uv;LatencyWindow<128>upload_latency,swap_latency;Clock::time_point last_debug{};
    bool init_gl(){program=make_program();if(!program)return false;glGenTextures(static_cast<GLsizei>(textures.size()),textures.data());for(GLuint t:textures){glBindTexture(GL_TEXTURE_2D,t);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_CLAMP_TO_EDGE);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE);}glGenBuffers(static_cast<GLsizei>(unpack_buffers.size()),unpack_buffers.data());pbo_ready=std::all_of(unpack_buffers.begin(),unpack_buffers.end(),[](GLuint id){return id!=0;});glBindBuffer(GL_PIXEL_UNPACK_BUFFER,0);glUseProgram(program);glUniform1i(glGetUniformLocation(program,"tex_y"),0);glUniform1i(glGetUniformLocation(program,"tex_u"),1);glUniform1i(glGetUniformLocation(program,"tex_v"),2);glUniform1i(glGetUniformLocation(program,"tex_uv"),3);nv12_uniform=glGetUniformLocation(program,"nv12");glUseProgram(0);return nv12_uniform>=0;}
    bool refresh_drawable_size(bool force=false){if(!window)return false;if(!force&&drawable_width>0&&drawable_height>0&&presented-last_size_refresh<8)return true;int w=0,h=0;if(!SDL_GetWindowSizeInPixels(window,&w,&h)||w<=0||h<=0)return drawable_width>0&&drawable_height>0;drawable_width=w;drawable_height=h;last_size_refresh=presented;return true;}
    void ensure_texture_storage(int w,int h){if(w==texture_width&&h==texture_height)return;texture_width=w;texture_height=h;const int cw=(w+1)/2,ch=(h+1)/2;glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_2D,textures[0]);glTexImage2D(GL_TEXTURE_2D,0,GL_LUMINANCE,w,h,0,GL_LUMINANCE,GL_UNSIGNED_BYTE,nullptr);glActiveTexture(GL_TEXTURE1);glBindTexture(GL_TEXTURE_2D,textures[1]);glTexImage2D(GL_TEXTURE_2D,0,GL_LUMINANCE,cw,ch,0,GL_LUMINANCE,GL_UNSIGNED_BYTE,nullptr);glActiveTexture(GL_TEXTURE2);glBindTexture(GL_TEXTURE_2D,textures[2]);glTexImage2D(GL_TEXTURE_2D,0,GL_LUMINANCE,cw,ch,0,GL_LUMINANCE,GL_UNSIGNED_BYTE,nullptr);glActiveTexture(GL_TEXTURE3);glBindTexture(GL_TEXTURE_2D,textures[3]);glTexImage2D(GL_TEXTURE_2D,0,GL_LUMINANCE_ALPHA,cw,ch,0,GL_LUMINANCE_ALPHA,GL_UNSIGNED_BYTE,nullptr);}
    bool upload_plane_pbo(std::size_t plane,GLenum unit,GLuint texture,GLenum format,int width,int height,const std::uint8_t*src,int stride,int bpp){if(!pbo_ready||plane>=4||!src||width<=0||height<=0||stride==0||bpp<=0)return false;const std::size_t row_bytes=static_cast<std::size_t>(width)*static_cast<std::size_t>(bpp),bytes=row_bytes*static_cast<std::size_t>(height);if(bytes==0)return false;const GLuint pbo=unpack_buffers[pbo_phase*4+plane];glBindBuffer(GL_PIXEL_UNPACK_BUFFER,pbo);glBufferData(GL_PIXEL_UNPACK_BUFFER,static_cast<GLsizeiptr>(bytes),nullptr,GL_STREAM_DRAW);auto*mapped=static_cast<std::uint8_t*>(glMapBuffer(GL_PIXEL_UNPACK_BUFFER,GL_WRITE_ONLY));if(!mapped){glBindBuffer(GL_PIXEL_UNPACK_BUFFER,0);return false;}for(int y=0;y<height;++y)std::memcpy(mapped+static_cast<std::size_t>(y)*row_bytes,src+static_cast<std::ptrdiff_t>(y)*stride,row_bytes);if(glUnmapBuffer(GL_PIXEL_UNPACK_BUFFER)!=GL_TRUE){glBindBuffer(GL_PIXEL_UNPACK_BUFFER,0);return false;}glActiveTexture(unit);glBindTexture(GL_TEXTURE_2D,texture);glPixelStorei(GL_UNPACK_ROW_LENGTH,0);glTexSubImage2D(GL_TEXTURE_2D,0,0,0,width,height,format,GL_UNSIGNED_BYTE,nullptr);glBindBuffer(GL_PIXEL_UNPACK_BUFFER,0);return true;}
    void upload_plane(std::size_t plane,GLenum unit,GLuint texture,GLenum format,int width,int height,const std::uint8_t*src,int stride,int bpp,std::vector<std::uint8_t>&scratch){if(!upload_plane_pbo(plane,unit,texture,format,width,height,src,stride,bpp))upload_plane_direct(unit,texture,format,width,height,src,stride,bpp,scratch);}
    void debug_timing(){if(!debug_enabled())return;const auto now=Clock::now();if(last_debug.time_since_epoch().count()!=0&&now-last_debug<std::chrono::seconds(1))return;last_debug=now;const auto upload=upload_latency.snapshot(),swap=swap_latency.snapshot();std::cerr<<"OPAL present upload_submit p50="<<upload.p50<<"ms p95="<<upload.p95<<"ms p99="<<upload.p99<<"ms swap_return p50="<<swap.p50<<"ms p95="<<swap.p95<<"ms p99="<<swap.p99<<"ms path="<<(pbo_ready?"pbo":"direct")<<" presentation="<<(immediate_swap?"immediate-active":"fallback")<<" photon_timing=unmeasured\n";}
};

VideoPresenter::VideoPresenter():impl_(std::make_unique<Impl>()){}
bool VideoPresenter::open(int sw,int sh,bool fullscreen){close();if(sw<=0||sh<=0)return false;impl_=std::make_unique<Impl>();SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER,1);SDL_GL_SetAttribute(SDL_GL_RED_SIZE,8);SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE,8);SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE,8);SDL_WindowFlags flags=SDL_WINDOW_OPENGL|SDL_WINDOW_RESIZABLE|SDL_WINDOW_HIGH_PIXEL_DENSITY;if(fullscreen)flags|=SDL_WINDOW_FULLSCREEN;impl_->window=SDL_CreateWindow("OPAL",sw,sh,flags);if(!impl_->window){close();return false;}impl_->context=SDL_GL_CreateContext(impl_->window);if(!impl_->context){close();return false;}if(!SDL_GL_MakeCurrent(impl_->window,impl_->context)){close();return false;}impl_->immediate_swap=SDL_GL_SetSwapInterval(0);if(impl_->immediate_swap){int interval=1;if(!SDL_GL_GetSwapInterval(&interval)||interval!=0)impl_->immediate_swap=false;}if(!impl_->init_gl()){close();return false;}glDisable(GL_DEPTH_TEST);glDisable(GL_CULL_FACE);glDisable(GL_DITHER);glPixelStorei(GL_UNPACK_ALIGNMENT,1);glClearColor(0.f,0.f,0.f,1.f);if(!impl_->refresh_drawable_size(true)){close();return false;}return true;}
bool VideoPresenter::present_borrowed(DecodedVideoView decoded){const AVFrame*f=decoded.frame;if(!f||!impl_||!impl_->window||!impl_->context||f->width<=0||f->height<=0)return false;const bool yuv420=f->format==AV_PIX_FMT_YUV420P||f->format==AV_PIX_FMT_YUVJ420P,nv12=f->format==AV_PIX_FMT_NV12;if(!yuv420&&!nv12)return false;if(!impl_->refresh_drawable_size())return false;const int ww=impl_->drawable_width,wh=impl_->drawable_height;glViewport(0,0,ww,wh);glClear(GL_COLOR_BUFFER_BIT);fitted_viewport(ww,wh,f->width,f->height);impl_->ensure_texture_storage(f->width,f->height);const auto upload_begin=Clock::now();impl_->upload_plane(0,GL_TEXTURE0,impl_->textures[0],GL_LUMINANCE,f->width,f->height,f->data[0],f->linesize[0],1,impl_->scratch_y);if(yuv420){const int cw=(f->width+1)/2,ch=(f->height+1)/2;impl_->upload_plane(1,GL_TEXTURE1,impl_->textures[1],GL_LUMINANCE,cw,ch,f->data[1],f->linesize[1],1,impl_->scratch_u);impl_->upload_plane(2,GL_TEXTURE2,impl_->textures[2],GL_LUMINANCE,cw,ch,f->data[2],f->linesize[2],1,impl_->scratch_v);}else{const int cw=(f->width+1)/2,ch=(f->height+1)/2;impl_->upload_plane(3,GL_TEXTURE3,impl_->textures[3],GL_LUMINANCE_ALPHA,cw,ch,f->data[1],f->linesize[1],2,impl_->scratch_uv);}const auto upload_end=Clock::now();impl_->upload_latency.push(elapsed_ms(upload_begin,upload_end));impl_->pbo_phase^=1;glUseProgram(impl_->program);glUniform1i(impl_->nv12_uniform,nv12?1:0);glBegin(GL_TRIANGLE_STRIP);glTexCoord2f(0.f,1.f);glVertex2f(-1.f,-1.f);glTexCoord2f(1.f,1.f);glVertex2f(1.f,-1.f);glTexCoord2f(0.f,0.f);glVertex2f(-1.f,1.f);glTexCoord2f(1.f,0.f);glVertex2f(1.f,1.f);glEnd();glUseProgram(0);const auto swap_begin=Clock::now();if(!SDL_GL_SwapWindow(impl_->window))return false;const auto swap_end=Clock::now();impl_->swap_latency.push(elapsed_ms(swap_begin,swap_end));++impl_->presented;impl_->debug_timing();return true;}
bool VideoPresenter::present(DecodedVideoFrame decoded){AVFrame*f=decoded.frame;if(!f)return false;const bool ok=present_borrowed({f,decoded.pts_us});av_frame_free(&f);return ok;}
std::pair<int,int> VideoPresenter::drawable_size()const{if(!impl_||!impl_->window)return{0,0};if(impl_->drawable_width>0&&impl_->drawable_height>0)return{impl_->drawable_width,impl_->drawable_height};int w=0,h=0;if(!SDL_GetWindowSizeInPixels(impl_->window,&w,&h))return{0,0};return{w,h};}
std::pair<int,int> VideoPresenter::window_size()const{if(!impl_||!impl_->window)return{0,0};int w=0,h=0;if(!SDL_GetWindowSize(impl_->window,&w,&h))return{0,0};return{w,h};}
bool VideoPresenter::set_relative_mouse_mode(bool enabled){if(!impl_||!impl_->window)return false;if(!SDL_SetWindowRelativeMouseMode(impl_->window,enabled))return false;if(!SDL_SetWindowMouseGrab(impl_->window,enabled))return false;return enabled?SDL_HideCursor():SDL_ShowCursor();}
std::size_t VideoPresenter::pending_frame_count()const{return 0;}
std::uint64_t VideoPresenter::presented_frames()const{return impl_?impl_->presented:0;}
std::string VideoPresenter::backend_name()const{const char*driver=SDL_GetCurrentVideoDriver();const std::string base=driver&&*driver?driver:"unconfigured";return impl_&&impl_->pbo_ready?base+"+opengl-pbo":base+"+opengl";}
std::string VideoPresenter::presentation_mode()const{return impl_&&impl_->immediate_swap?"immediate-active":"fallback";}
bool VideoPresenter::is_open()const{return impl_&&impl_->window&&impl_->context;}
void VideoPresenter::close(){if(!impl_)return;if(impl_->window){(void)SDL_SetWindowMouseGrab(impl_->window,false);(void)SDL_SetWindowRelativeMouseMode(impl_->window,false);(void)SDL_ShowCursor();}if(impl_->window&&impl_->context){SDL_GL_MakeCurrent(impl_->window,impl_->context);glBindBuffer(GL_PIXEL_UNPACK_BUFFER,0);if(impl_->unpack_buffers[0]){glDeleteBuffers(static_cast<GLsizei>(impl_->unpack_buffers.size()),impl_->unpack_buffers.data());impl_->unpack_buffers.fill(0);}if(impl_->program){glDeleteProgram(impl_->program);impl_->program=0;}if(impl_->textures[0]){glDeleteTextures(static_cast<GLsizei>(impl_->textures.size()),impl_->textures.data());impl_->textures.fill(0);}}if(impl_->context){SDL_GL_DestroyContext(impl_->context);impl_->context=nullptr;}if(impl_->window){SDL_DestroyWindow(impl_->window);impl_->window=nullptr;}}
VideoPresenter::~VideoPresenter(){close();}
}